### ISSUE TITLE
AWS Load Balancer Type

### ISSUE THREAD

**Issue by miclip** [pivotal-cf/docs-pcf-install#102]
It's not clear which Load Balancer Type to select when manually configuring PCF on AWS.

https://docs.pivotal.io/pivotalcf/1-9/customizing/pcf-aws-manual-config.html#pcfaws-lb

<img width="1225" alt="screen shot 2017-01-16 at 4 50 17 pm" src="https://cloud.githubusercontent.com/assets/6088771/22000255/248afe22-dc0c-11e6-9801-8426f283d94b.png">

**Comment by pspinrad** [comment]
@miclip Classic -- adding to the docs.
