### ISSUE TITLE
Step 13 of Elastic Runtime on GCP install docs should talk about the default project for interoperable access

### ISSUE THREAD

**Issue by mattbnz** [pivotal-cf/docs-pcf-install#103]
Following http://docs.pivotal.io/pivotalcf/1-9/customizing/gcp-er-config.html#filestore to install PCF my initial deploy failed because I already had a different project selected in the "default project for interoperable access" field than the project I was installing PCF into. This wasn't necessarily intentional, I just skipped over that part of the page because it wasn't mentioned in the instructions. 

I suggest adding a sentence to Step 13, e.g. within point 3 after the sentence about enabling interoperable access add:

If interoperable access is already enabled, check that the default project setting matches the project you are installing PCF into as shown in the screenshot below.

or similar.

**Comment by animatedmax** [comment]
Hi @mattbnz We added a bullet in http://docs.pivotal.io/pivotalcf/1-9/customizing/gcp-er-config.html#filestore -- Step 13, #2 "If necessary, click Enable interoperability access. If interoperability access is already enabled, confirm that the default project matches the project where you are installing PCF." 
Thank you for raising this issue
