### ISSUE TITLE
Preparing to Deploy PCF on GCP should link to the GCP reference architecture

### ISSUE THREAD

**Issue by wendorf** [pivotal-cf/docs-pcf-install#104]
In my experience with helping people install on GCP, the overview of the reference architecture is sometimes missed when on `gcp-prepare-env.html.md.erb` (perhaps because people are going straight to that page from an external link). Because that is the page that is walking through setting up the architecture, it would be helpful to have a link to the reference architecture page like there is on `gcp.html.md.erb`.

Thanks!

**Comment by scribblingfox** [comment]
Hi there @wendorf! I've got this edit in progress and hope to have it up in production today. :) Thanks for calling this to our attention!
