### ISSUE TITLE
Deploying Elastic Runtime on GCP should have a post-install note guiding the user to next steps

### ISSUE THREAD

**Issue by wendorf** [pivotal-cf/docs-pcf-install#106]
In my experience with people new to PCF, they sometimes get to the end of `gcp-er-config.html.md.erb` and don't know next steps (e.g. how to find out the URL for their API for targeting).

My suggestion is to have a section saying something to the effect of "Congrats, now you've got an ERT. Now check out the [Operators Guide](https://github.com/pivotal-cf/docs-ops-guide/blob/1.9/index.html.md.erb)!".

**Comment by animatedmax** [comment]
Thank you @wendorf We're looking into new tools that will create these links automatically, and into creating better signposts so people know where they are and where they need to go next in a long process.
