### ISSUE TITLE
Wrong configurations about TCP Router on GCP

### ISSUE THREAD

**Issue by making** [pivotal-cf/docs-pcf-install#110]
I had a few troubles with TCP Routing on GCP / PCF 1.10.0.

### Health Check

Health check for TCP router is not as same as WebSocket's.

![image](https://cloud.githubusercontent.com/assets/106908/24079003/c8c82f5c-0cc0-11e7-9e9e-e2ea1e44a32f.png)

`80` port is correct for TCP Router's health check.

### Target Tag

`pcf-cf-tcp` does not exist in tcp router's tags. So firewall seems to block routing to tcp_router VM.

![image](https://cloud.githubusercontent.com/assets/106908/24079016/2d54a248-0cc1-11e7-9124-46c1209923d4.png)

![image](https://cloud.githubusercontent.com/assets/106908/24079025/5fa89786-0cc1-11e7-8078-40287de9b848.png)

After changing the target tag to `pcf-tcp-router`, it works.

**Comment by animatedmax** [comment]
Hi @making We update http://docs.pivotal.io/pivotalcf/1-10/customizing/gcp-prepare-env.html to address this issue. Thank you for bringing it to our attention.
