### ISSUE TITLE
ERT instructions for Azure are missing a required database

### ISSUE THREAD

**Issue by guidowb** [pivotal-cf/docs-pcf-install#112]
(reported by a partner)

http://docs.pivotal.io/pivotalcf/1-10/customizing/azure-er-config.html#create-dbs

Does not list the `networkpolicyserver` database that seems to be required by ERT 1.10.2 (and possibly earlier versions, I have not attempted those). Not creating that database results in the error:

```
Database verification error: Unknown database 'networkpolicyserver'

Started updating instance cloud_controller > cloud_controller/35b6d54c-4c20-4fbe-a065-d9eca6b950e1 (0) (canary). Failed: 'cloud_controller/0 (35b6d54c-4c20-4fbe-a065-d9eca6b950e1)' is not running after update. Review logs for failed jobs: policy-server (00:06:03)

Error 400007: 'cloud_controller/0 (35b6d54c-4c20-4fbe-a065-d9eca6b950e1)' is not running after update. Review logs for failed jobs: policy-server
```

**Comment by seviet** [comment]
Thanks for reporting this. Yes, this DB should be created when deploying an external DB in 1.10. Added a step for all the IaaSes.
