### ISSUE TITLE
Internal UAAC Login

### ISSUE THREAD

**Issue by jasonodonnell** [pivotal-cf/docs-pcf-install#113]
The [instructions for logging](https://github.com/pivotal-cf/docs-pcf-install/blob/1.10/trouble-advanced.html.md.erb#L120) into the internal `UAAC` in the advanced troubleshooting guidance has an IP address which is confusing:

```bash
$ bosh --ca-cert /var/tempest/workspaces/default/root_ca_certificate target 192.0.2.6
```

IMO this should be (like the previous example in that doc):

```bash
$ bosh --ca-cert /var/tempest/workspaces/default/root_ca_certificate target DIRECTOR-IP-ADDRESS
```

Thanks!

**Comment by bentarnoff** [comment]
Thanks for submitting the PR (https://github.com/pivotal-cf/docs-pcf-install/pull/114) to update this. Closing.
