### ISSUE TITLE
Step 2: Add Elastic Runtime to Ops Manager-- file upload issue

### ISSUE THREAD

**Issue by sushil2226** [pivotal-cf/docs-pcf-install#116]
Hi Team,

Reference link: https://docs.pivotal.io/pivotalcf/1-10/customizing/cloudform-er-config.html
While installing PCF on AWS ,as mentioned in Step2, download and import Elastic Runtime file(*.pivotal) size of approx 6GB takes very long time and mostly it gets fail while uploading.

Can you please suggest an alternative to it as this documentation process does not succeed ?

Thanks,
Sushil

**Comment by bentarnoff** [comment]
Hey @sushil2226 I'm afraid that the Elastic Runtime pivotal file is simply a large file. I'd recommend using Ethernet rather than wifi when downloading and uploading it. I'm closing this issue for now but feel free to get in touch with any further concerns or questions.
