### ISSUE TITLE
"Step 7: Configure Application Containers" does not include DNS server config option that went in with 1.10.8

### ISSUE THREAD

**Issue by marie-cd** [pivotal-cf/docs-pcf-install#117]
1.10.8 added a feature that "Allows operators to specify DNS servers that differ from those provided in their BOSH configuration." (https://docs.pivotal.io/pivotalcf/1-10/pcf-release-notes/runtime-rn.html#1.10.8)

Our documentation doesn't reflect this yet. Please update the "Step 7: Configure Application Containers" section to include a note that this is an option.

**Comment by ljarzynski** [comment]
Thanks for bringing this to our attention @marie-cd ! I'm working on this now.
