### ISSUE TITLE
"Step 10: Configure Authentication and Enterprise SSO" in AWS documentation does not contain info about Service Provider Credentioals and Service Provider Password

### ISSUE THREAD

**Issue by dgur1n** [pivotal-cf/docs-pcf-install#118]
I'm installing PCF on AWS  and deploying Elastic Runtime v1.10.8 build 7 using this [doc](https://docs.pivotal.io/pivotalcf/1-10/customizing/cloudform-er-config.html#er-auth-config). Step 10 requires to specify Service Provider Credentials and Service Provider Password. Couldn't find info about it in documentation. Attached screenshot.
Could you please add it?
Thanks,
Daniil.
![pcf_authentication_config](https://cloud.githubusercontent.com/assets/7850003/25998005/ad146c1c-3727-11e7-8efe-e3c2f8220be7.png)

**Comment by bentarnoff** [comment]
Hey @dgur1n the topic has been updated with the correct information. Thanks.
