### ISSUE TITLE
Azure CLI Commands

### ISSUE THREAD

**Issue by mfdellinger** [pivotal-cf/docs-pcf-install#119]
I was going through the steps on Doc 1.10 and although the Azure CLI commands were technically correct...A lot of the parameters to the commands were incorrect in your samples...  I was also using Azure CLI 2.0 which I think your samples are from 1.0.

**Comment by bentarnoff** [comment]
Hey @mfdellinger thanks for bringing this to our attention. All of the procedures in our Azure documentation require the Azure CLI 1.0. They won't work with the Azure CLI 2.0. We will add clarifying notes to that effect in our documentation. Thanks.
