### ISSUE TITLE
Steps for Azure ARM Template 

### ISSUE THREAD

**Issue by nevenc-pivotal** [pivotal-cf/docs-pcf-install#126]
It seems the documentation is outdated (and misleading):
https://github.com/pivotal-cf/docs-pcf-install/blob/1.10/azure-arm-template.html.md.erb

1) `opsmanager` container is not needed for deployment storage accounts. (line 175-177)
2) `stemcell` container does not need to be a public blob container (can't use public in PLRS) (line 182)

**Comment by bentarnoff** [comment]
Hey @nevenc-pivotal thanks for this. It looks like you took care of this with your PR (https://github.com/pivotal-cf/docs-pcf-install/pull/127). Closing.
