### ISSUE TITLE
Azure Marketplace screenshot of PCF has been deprecated

### ISSUE THREAD

**Issue by pivotal-manuel-morales** [pivotal-cf/docs-pcf-install#129]
The docs for Azure Install shows an outdated screenshot. See Step 3 - https://docs.pivotal.io/pivotalcf/1-10/customizing/pcf_azure.html#getting-started

I have included what the Microsoft looks like now.
![new azure marketplace](https://cloud.githubusercontent.com/assets/22778970/26657474/e3c892a6-4618-11e7-9d5f-91a3da16ef3a.jpeg)

**Comment by pivotal-manuel-morales** [comment]
When logged into the Marketplace you do not see Deploy but instead Create.

![azure create pcf](https://cloud.githubusercontent.com/assets/22778970/26657765/c44d5a90-461a-11e7-822f-bd9e665608b6.jpeg)

**Comment by seviet** [comment]
@pivotal-manuel-morales Thank you for reporting this! I updated the screenshot and the directions. Let us know if you have additional feedback!
