### ISSUE TITLE
azure-prepare-env.html.md.erb References Old Cli

### ISSUE THREAD

**Issue by stevewallecs** [pivotal-cf/docs-pcf-install#131]
The Azure preparation document reference the old version of the Azure cli. This was a bit confusing until I figured out I needed to download the old version. This document should probably be updated to reflect the new cli.

**Comment by bentarnoff** [comment]
Thanks @stevewallecs. We've updated the docs on our staging site to use the Azure CLI v2, and they should be live on our production site soon.
