### ISSUE TITLE
Unable to find Uaa Bbr Client Credentials in Ops Manager

### ISSUE THREAD

**Issue by sudhindrarao** [pivotal-cf/docs-pcf-install#139]
I am unable to find the Uaa Bbr Client Credentials  in Ops Manager -> Director -> credentials section.

**Comment by bentarnoff** [comment]
Thanks @sudhindrarao. @thereses can you please confirm the name of the BBR credentials in the Ops Manager Credentials tab?

**Comment by bentarnoff** [comment]
Hey @sudhindrarao I just looked at a PCF 1.11 deployment and I can see `Uaa Bbr Client Credentials` when I navigate to Ops Manager Director and click the Credentials tab.

**Comment by sudhindrarao** [comment]
Ben
Interesting - all  I see is uaa login and client credential.  I don't see
it.  I swear I installed PCF 1.11 GA code.  May be can we screen share
tomorrow ?
