### ISSUE TITLE
Instructions refer to Ruby BOSH, which is deprecated

### ISSUE THREAD

**Issue by pivotal-jwynne** [pivotal-cf/docs-pcf-install#142]
For example: https://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/backup-pcf.html#-target-the-bosh-director

Docs should presumably recommend BOSH CLI v2 these days: https://github.com/cloudfoundry/bosh-cli

**Comment by bentarnoff** [comment]
Hey @pivotal-jwynne thanks for this. We're not yet documenting the BOSH CLI v2 in our PCF docs, although we do mention in the Ops Manager v1.11 Release Notes that the BOSH CLI v2 is packaged with the OM appliance, along with the CLI v1. We will most likely document the BOSH CLI v2 for the next major release of PCF. I'm closing this issue but please feel free to get in touch with any further feedback.
