### ISSUE TITLE
Duplicated steps in backup docs

### ISSUE THREAD

**Issue by pivotal-jwynne** [pivotal-cf/docs-pcf-install#144]
The steps from [Target the BOSH Director](https://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/backup-pcf.html#-target-the-bosh-director) are duplicated in the initial steps of [Download BOSH Manifest](https://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/backup-pcf.html#download-bosh-manifest)

This is confusing and doesn't read well.

**Comment by bentarnoff** [comment]
Hey @pivotal-jwynne thanks for bringing this to our attention. We've updated the topics accordingly.
