### ISSUE TITLE
Pivotal MySQL backup instructions SSH issues 

### ISSUE THREAD

**Issue by pivotal-jwynne** [pivotal-cf/docs-pcf-install#146]
http://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/backup-pcf.html#backup-mysql

This page gives incomplete and incorrect instructions for SSHing to the MySQL node. We think that in the modern era one would use `bosh ssh` and `bosh scp` to achieve this, without the need for grabbing credentials and addresses from OpsMan.

The instructions given for SSH in any case did not work. Firstly, it asks the reader to use the MySQL Admin credentials to use for SSH. This is incorrect - those credentials are for MySQL only. Attempting to do a bare `ssh` gave us:

```
$ ssh vcap@10.1.0.16
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Permission denied (publickey).
```

**Comment by pivotal-jwynne** [comment]
By the way, we found `mysqldump` was not on our path when we did SSH.

```
bosh -e myenv -d mysql-deadbeef ssh somejob # how we SSHd
sudo -i # We can do this! Somewhat surprising.
su vcap
/var/vcap/packages/mariadb/bin/mysqldump # Here it is! We managed to perform a backup using this executable.
```

**Comment by animatedmax** [comment]
https://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/backup-pcf.html#backup-mysql
