### ISSUE TITLE
opsmanager-create-bosh-client.html: Typo in permission name

### ISSUE THREAD

**Issue by amitkgupta** [pivotal-cf/docs-pcf-install#155]
It says to add `bosh admin` permissions, but it should say `bosh.admin`:

https://github.com/pivotal-cf/docs-pcf-install/blob/1da05caf196194677a6a79a152c0d41c0bf853a6/opsmanager-create-bosh-client.html.md.erb#L53

**Comment by chaueter** [comment]
Hi there,

Sorry to crash this party, but I've not been a member of Pivotal for over a
year now, and I'm not able to unsubscribe from `pivotal-cf` emails. Would
someone please do me the favor of removing me from any `pivotal-cf`
notification settings?

Thanks!

Chris

**Comment by Amit-PivotalLabs** [comment]
Hey @chaueter I believe you are receiving notifications because you are watching this repository: https://github.com/pivotal-cf/docs-pcf-install/watchers?page=2.  You can opt out of this, I don't believe anyone is able to do this on your behalf.

**Comment by chaueter** [comment]
Thanks @Amit-PivotalLabs, after some email client archeology, I regained access to that account and was able to disable the subscriptions. 👍
