### ISSUE TITLE
[bosh-cli-v2] opsmanager-create-bosh-client.html: "bosh target" command will change with new CLI

### ISSUE THREAD

**Issue by amitkgupta** [pivotal-cf/docs-pcf-install#157]
In OM 1.12, OM plans to ship with the new Golang BOSH CLI v2.x, and possibly won't include the old Ruby BOSH CLI at all.  Lots of documentation will need to change.  E.g. the 1.12 version of:

https://github.com/pivotal-cf/docs-pcf-install/blob/1da05caf196194677a6a79a152c0d41c0bf853a6/opsmanager-create-bosh-client.html.md.erb#L81

which currently says:

```
bosh --ca-cert /var/tempest/workspaces/default/root_ca_certificate \
target OPS-MANAGER-DIRECTOR-IP
```

will need to change to something like:

```
bosh --ca-cert /var/tempest/workspaces/default/root_ca_certificate --environment OPS-MANAGER-DIRECTOR-IP alias-env SOME-ENV-NAME
```

with subsequent commands being run as:

```
bosh -e SOME-ENV-NAME <command>
```

**Comment by animatedmax** [comment]
https://docs.pivotal.io/pivotalcf/1-11/customizing/opsmanager-create-bosh-client.html
