### ISSUE TITLE
[bosh-cli-v2] Advanced Troubleshooting page will need significant overhaul for 1.12

### ISSUE THREAD

**Issue by amitkgupta** [pivotal-cf/docs-pcf-install#158]
In OM 1.12, OM plans to ship with the new Golang BOSH CLI v2.x, and possibly won't include the old Ruby BOSH CLI at all.  Lots of documentation may need to change.  E.g. the 1.12 version of:

https://docs.pivotal.io/pivotalcf/1-11/customizing/trouble-advanced.html

currently has many BOSH CLI v1-isms.

/cc @sadvani @cppforlife

**Comment by animatedmax** [comment]
Added BOSH v2 instructions: https://docs.pivotal.io/pivotalcf/1-11/customizing/trouble-advanced.html
