### ISSUE TITLE
Azure troubleshooting doc has awkward instructions for fixing ERT issues

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#159]
`azure-troubleshooting.html.md.erb` has an issue in that it describes a way to deal with ALB disconnecting active TCP connections by doing some stuff with the BOSH CLI.

This is not an Ops Manager issue.  The other two issues on the page pertain to OM, but this pertains to ERT, so should probably move to a different doc.  This doc has `owner: Ops Manager`.

Furthermore, the solution instructions are not good.  ERT natively supports fixing this by setting the "Router Timeout to Backends (in seconds)" field in the "Networking" form for ERT to 180, the operator doesn't need to hack the manifest. [[details](https://github.com/pivotal-cf/p-runtime/blob/59f047dccaf282c1576195c3b14f549f1512a58e/metadata_parts/forms_and_validators/networking.yml#L146-L151)]

**Comment by animatedmax** [comment]
https://docs.pivotal.io/pivotalcf/1-11/customizing/azure-troubleshooting.html
