### ISSUE TITLE
[bosh-cli-v2] _bosh_target_director_manual.html.md.erb: will need update for OM 1.12

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#160]
This doc partial reference Ruby CLI v1, and in 1.12 we'll want users to use Golang CLI v2, so this doc will need some updates.

1. No need to install Ruby
2. New CLI installation instructions are at this link: http://bosh.io/docs/cli-v2.html#install
3. `bosh target` no longer exists, and `bosh login` command has some required flags.

/cc @cppforlife

**Comment by animatedmax** [comment]
Added BOSH v2 instructions: https://docs.pivotal.io/pivotalcf/1-11/customizing/backup-restore/restore-pcf.html
