### ISSUE TITLE
[bosh-cli-v2] mysql_bootstrap_ert.html.md.erb should get CLI instruction update for 1.12

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#162]
This doc references a lot of BOSH CLI v1 commands/workflows, and should be updated to reference BOSH CLI v2 ways of doing things.

One odd thing is it says "This topic requires you to run commands from the Ops Manager Director using the BOSH CLI.  This seems inaccurate, the commands would be run from Ops Manager itself, not the Director.  The commands would *target* the Director.

Aside from that, `bosh target` no longer exists, `bosh download manifest` is `bosh manifest`, and there are other misc changes to command names, required flags, and arguments.  One workflow difference is that you no longer `target` and `login` such that the CLI keeps state of your session.  You'll either need to set the `BOSH_ENVIRONMENT` variable up front, or include `-e` flag on all commands. /cc @cppforlife

**Comment by mjgutermuth** [comment]
Thanks @Amit-PivotalLabs! I updated all the BOSH commands on this page based on the CLI v2 docs. Let me know if you still see anything that doesn't look right.
