### ISSUE TITLE
Screen Shot and Instructions don't match GCP console

### ISSUE THREAD

**Issue by asaikali** [pivotal-cf/docs-pcf-install#165]
http://docs.pivotal.io/pivotalcf/1-8/customizing/gcp-prepare-env.html#instance_group
Step 6 says 

Under Creation method, choose Select existing instance and select opsmgr from the Network drop-down. You previously created the opsmgr network in the Create a GCP Network with Subnet step above. 

The instructions don't match what I see on GCP there is no Creation Mothed it's now called Group Type and it looks like Unmanaged instance group might be the correct choice.

**Comment by bentarnoff** [comment]
Thanks, @asaikali! We confirmed with Customer0 that the operator wants the "Unmanaged instance group" here. We are updating the text and the screenshot for all available PCF on GCP docs, and the changes will be live soon. Thanks again.
