### ISSUE TITLE
Broken link: Proxy partial needs to be versioned

### ISSUE THREAD

**Issue by menicosia** [pivotal-cf/docs-pcf-install#168]
Check out line 110 of [configure-er-vmware.html](https://github.com/pivotal-cf/docs-pcf-install/blob/1.11/config-er-vmware.html.md.erb#L110). It's a directive to load a partial.

If you look at the [rendered version](https://docs.pivotal.io/pivotalcf/1-11/customizing/config-er-vmware.html#internal-mysql) of that section, you'll see a link to the Proxy:

> See the [Proxy](http://docs.pivotal.io/p-mysql/index.html#proxy) section of the MySQL for PCF topic for more information.

Unfortunately, default p-mysql docs point to v2, which contains no proxy nor proxy documentation. So it's a broken link.

**Comment by bentarnoff** [comment]
@menicosia Thanks for this. Should we instead be linking users to the "MySQL Proxy" topic in the MySQL for PCF 1.9 docs? http://docs.pivotal.io/p-mysql/1-9/proxy.html

**Comment by menicosia** [comment]
Yeah, 1.9 is certain to be supported at least through January of next year,
so it's a pretty safe bet (for now).

**Comment by bentarnoff** [comment]
Thanks @menicosia. I've made this change to all available versions of our PCF docs, and it should be live on our prod site soon.
