### ISSUE TITLE
update upgrading-pcf.html.md.erb to describe 1.5.0

### ISSUE THREAD

**Issue by factorypreset** [pivotal-cf/docs-pcf-install#17]
upgrading-pcf currently describes upgrading to v1.4.0 of Ops Manager. Can it be updated to describe the process of upgrading to 1.5.0?

**Comment by kimahoff** [comment]
Hi @factorypreset,
We updated this topic for our last release. It now describes upgrading from 1.5 to 1.6, which is the most current upgrade path. If you have any other feedback or spot other issues, please let us know!

Thanks,
The PCF documentation team
