### ISSUE TITLE
Error in the tags applied to GCP firewall rules

### ISSUE THREAD

**Issue by cdavisafc** [pivotal-cf/docs-pcf-install#174]
I followed these docs (http://docs.pivotal.io/pivotalcf/1-11/customizing/gcp-prepare-env.html) in configuring my GCP environment for a PCF deploy. My bosh director failed to install properly. After some troubleshooting I believe the problem to be incorrect tags on a firewall rule.

I looked back at the tags and found an odd thing in the docs: http://docs.pivotal.io/pivotalcf/1-11/customizing/gcp-prepare-env.html#firewall_rules - in Step 5 it says to name the tcp load balancer pcf-tcp-lb but then says to tag it pcf-tcp-router. I initially followed that instruction but last night I added the tag pcf-tcp-lb and started from the top - installed a new OM, configured the GCP tile and applied changes. Boom! This morning when I woke I had a functioning BOSH director.

**Comment by animatedmax** [comment]
Thank you, cdavisafc !

We've corrected the tag in this topic, and in the same topic in v1.10, v1.9, and v1.8.
