### ISSUE TITLE
Configure Email Notifications: SMTP on GCP 

### ISSUE THREAD

**Issue by GarimaSharma** [pivotal-cf/docs-pcf-install#177]
Docs mention [port 587 while configuring SMTP on GCP](https://docs.pivotal.io/pivotalcf/1-11/customizing/gcp-er-config.html). However [port 25 and port 587 are not allowed on Compute Engine](https://cloud.google.com/compute/docs/tutorials/sending-mail/using-sendgrid).

It should be mention there, stating port 2525 will work on PCF on GCP.

Raising an issue instead of pull request because it would require to change the screenshot of "email configuration section" as well.

**Comment by animatedmax** [comment]
Thank you, GarimaSharma !

**Comment by animatedmax** [comment]
We've updated the page to reflect this restriction: http://docs.pivotal.io/pivotalcf/1-11/customizing/gcp-er-config.html#smtp
