### ISSUE TITLE
NSX CA not always optional for Ops Manager NSX configuration

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#178]
Says it's optional [here](https://github.com/pivotal-cf/docs-pcf-install/blob/e70f2e5a71d9fc8dc92e3aad185440d6147bfcac/vsphere-config.html.md.erb#L74), but it's actually a bit more subtle.  BOSH docs [here](https://bosh.io/docs/vsphere-cpi.html#global) say:

> * **ca_cert** [String, optional]: A CA certificate that can authenticate the NSX server certificate. **Required** if the NSX Manager has a self-signed SSL certificate. Must be in PEM format.

I also actually wonder whether even the BOSH docs are correct, and even if the NSX Manager has an SSL cert signed by a separate CA, if BOSH doesn't already trust that CA then it would need to be added in this configuration as well. /cc @cppforlife 

/cc @sadvani @mjgutermuth

**Comment by animatedmax** [comment]
http://docs-pcf-staging.cfapps.io/pivotalcf/1-12/customizing/vsphere-config.html#vcenter-config
http://docs-pcf-staging.cfapps.io/pivotalcf/1-11/customizing/vsphere-config.html#vcenter-config
