### ISSUE TITLE
AWS Documentation Missing Databases

### ISSUE THREAD

**Issue by jasonodonnell** [pivotal-cf/docs-pcf-install#184]
When using external databases on AWS (such as RDS MYSQL), [you need to create a bunch of databases.](https://docs.pivotal.io/pivotalcf/1-11/customizing/cloudform-er-config.html#sys-db)  Two databases are missing from this list though:

```sql
CREATE DATABASE silk;
CREATE DATABASE locket;
```

**Comment by animatedmax** [comment]
We have added these databases to the list. Thank you, @jasonodonnell
