### ISSUE TITLE
Remove instruction to generate SSH key in advanced troubleshooting

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#216]
These can be removed:

https://github.com/pivotal-cf/docs-pcf-install/blob/39aac8250c9385bae05d54a445407e77683edaa3/trouble-advanced.html.md.erb#L277-L278

User doesn't need to do it, the subsequent commands don't even use the generated key.

**Comment by animatedmax** [comment]
Thanks, @Amit-PivotalLabs
