### ISSUE TITLE
Azure External DB says AWS RDS

### ISSUE THREAD

**Issue by mxplusb** [pivotal-cf/docs-pcf-install#217]
It should say Azure MySQL instead of AWS RDS.

https://docs.pivotal.io/pivotalcf/1-12/customizing/azure-er-config.html#create-dbs

**Comment by animatedmax** [comment]
Hi @mxplusb  
The procedure shown uses AWS RDS as an example. The exact procedure to create databases depends upon the database provider you select for your deployment.
