### ISSUE TITLE
Should not assume availabillity of "local linux workstation"

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/docs-pcf-install#218]
In trouble-advanced.html.md.erb your docs say:

>  If you do not have browser access to the BOSH Director, run `sshuttle` on a local Linux workstation to
> browse the BOSH Director IP address as if it were a local address. Retrieve a UAA passcode using the 
>  browser:
>      <pre class='terminal'>
>     $ git clone https:<span>//</span>github.com/apenwarr/sshuttle.git
>      $ cd sshuttle
>      $ ./sshuttle -r username@opsmanagerIP 0.0.0.0/0 -vv
>      </pre>

I have two issues with this:
1. Assuming that a "local linux workstation" is available upon which to run sshuttle is a bad assumption.  Corporate environments often do not allow such devices.  You cannot assume their availability.
2. Suggesting the user install  and use a piece of software from a not-Pivotal github repo is a bad assumption  If your software has this sort of challenging issue in it, Pivotal should provide the workaround not an external random-appearing repo.

On point 1. You would do better to suggest using an ssh port forwarding solution supported by PuTTY, FSecure, or other available SSH software.  that would obviate the need for point 2.

**Comment by mlimonczenko** [comment]
Thank you, @labrown!
