### ISSUE TITLE
OpsManager VM AWS AMI

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [pivotal-cf/docs-pcf-install#219]
Hi there,

I am having currently a problem with manually setting up a PCF (1.11) on AWS. 
When configuring the OpsManager Director AWS settings I am trying to use an AWS Instance Profil. 
After entering the name I got the following error message:

Could not log in: Please give OpsMan the iam:GetInstanceProfile permission for the requested instance profile: pcf-user

Does the OpsManager VM need an IAM Role to be able to access the pcf-user profile? If so, this part is missing in the documentation. 

Using AccessKeyID and Secret Key works.

**Comment by cshollingsworth** [comment]
Hi, Ben! You're correct: an IAM role is needed to access the pcf-user profile. We added an instruction to select/create the IAM role.
