### ISSUE TITLE
Known Issues link doesn't point to known installation issues

### ISSUE THREAD

**Issue by sumkincpp** [pivotal-cf/docs-pcf-install#226]
"Known Issues" link doesn't link to known installtion issues on deploying VM page, i.e. on
https://github.com/pivotal-cf/docs-pcf-install/blob/1.12/deploying-vm.html.md.erb

Though the installation issues are stored in Knowledgebase with all of the known issues
https://discuss.pivotal.io/hc/en-us/sections/206852568-Ops-Manager

**Comment by animatedmax** [comment]
Hi @sumkincpp Thank you for pointing out this incorrect link. The intended target of the Known Issues link in the particular topic is https://docs.pivotal.io/pivotalcf/1-11/pcf-release-notes/opsmanager-rn.html#knownissues and we're making sure to correct this in the other versions (1.12, 1.10, 1.9, etc.) of this topic, too.
