### ISSUE TITLE
load balancer backend pool name mismatch

### ISSUE THREAD

**Issue by tacowan** [pivotal-cf/docs-pcf-install#227]
Step 3.6  “pcf-vms”

The elastic runtime small footprint creates a different backend pool with a different name…notice in the documentation it has us setup 3 different load balancing rules (ssh, http, https).  Those are attached to pcf-vms which is never used by elastic runtime.  I think the name of the backend pool just needs to be changed to “pcf-lbbepool” which is what elastic uses.

Change “pcf-vms” to “pcf-lbbepool”

**Comment by seviet** [comment]
hey @tacowan! could you indicate which .html.md.erb file requires this update? thanks so much!

**Comment by tacowan** [comment]
Hi, here you go: https://github.com/pivotal-cf/docs-pcf-install/blob/1.12/azure-om-deploy.html.md.erb

where it has the code "--name pcf-vms "...the actual backend pool name elastic small footprint used was “pcf-lbbepool” so I'd have expected "--name pcf-lbbepool".  Things worked once I made this change to the load balancer.

**Comment by seviet** [comment]
thank you so much @tacowan! this has been fixed here: 
http://docs.pivotal.io/pivotalcf/1-12/customizing/azure-om-deploy.html#lb
