### ISSUE TITLE
Clarify docs wrt stemcell restore

### ISSUE THREAD

**Issue by zmb3** [pivotal-cf/docs-pcf-install#234]
Under the restore docs, __Step 4: Remove the bosh state file__, we have:

> For each tile that requires one, upload the required stemcell.

Then later in in __Step 10: Redeploy Elastic Runtime__, we instruct the user to find the stemcell for ERT and uploaded it.  Wasn't this already covered by the previous step?

**Comment by cshollingsworth** [comment]
Hi! The stemcells referenced in Step 4 and Step 11 were meant to be stemcells for different tiles. The Step 4 stemcell is the stemcell used by the BOSH Director deployment and any other stemcells for tiles that are directly deployed by Ops Manager. The stemcell in Step 11 is specifically for ERT. We clarified this distinction in the documentation.

**Comment by zmb3** [comment]
The docs are still confusing to me.  ERT **is** a tile directly deployed by ops manager.

**Comment by cshollingsworth** [comment]
Added further clarification:

"4. Upload the required stemcell for each tile that requires one, excluding ERT. You will upload the stemcell for ERT in Step 11."
