### ISSUE TITLE
Azure Configure Ops Manager Director 1.12 "default" network is not created but needs to be selected.

### ISSUE THREAD

**Issue by hijglander** [pivotal-cf/docs-pcf-install#257]
Just started the configuration of Ops Manager Director 1.12 on Azure, when arriving at "Step 5: Assign Networks Page" the network "default" needs to be selected. This network is not created nor is it selectable. Please update this topic.

**Comment by OpusDude** [comment]
Ran into the same issue. You need to select the '**Management**' network in the drop down.

https://github.com/pivotal-cf/docs-pcf-install/blob/1.12/azure-om-config.html.md.erb#L204

**Comment by animatedmax** [comment]
Hi @hijglander and @OpusDude We've updated the following topic based on your feedback: 
http://docs.pivotal.io/pivotalcf/1-12/customizing/azure-om-config.html#assign-networks

Thanks!
