### ISSUE TITLE
This needs updated to use Azure CLI 2.0

### ISSUE THREAD

**Issue by vseanclark** [pivotal-cf/docs-pcf-install#258]
Creating the Service Principle JSON file uses the old Azure CLI client.  This needs to be updated to leverage Azure CLI 2.0.

**Comment by vseanclark** [comment]
Instead of pointing folks to the old Azure CLI and the azure-sp-tool, what about just sharing the format that is expected for the json credential file?   I ran the old tool and looked at the contents of azure-credentials.json, which you can see below.  I replaced the values with the ones I created via AzureCLI 2.0 and started the deployment of PCF through the portal using my lovingly created azure-credentials.json.  It seems to be deploying everything I need.  

{
    "subscriptionID": "blahblahsubscriptionId",
    "tenantID": "blahblahtenantIDgoeshere",
    "clientID": "blahblahServicePrincipleID/NamegoesHere",
    "clientSecret": "SP password goes here"
}

Cheers!

**Comment by seviet** [comment]
Thanks @vseanclark This has been fixed. Please feel to open up another issue or PR if you have more feedback!
