### ISSUE TITLE
Suggestions for better DNS config on gcp-om-config.html.md.erb

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pivotal-cf/docs-pcf-install#261]
The suggested configurations below haven't been tested, but I wanted to capture them somewhere so we can start a discussion.

* NTP configuration: [this line](https://github.com/pivotal-cf/docs-pcf-install/blob/2a86a6a6e43e9b5ea1476ace1aa82bc775611ab5/gcp-om-config.html.md.erb#L65) mentions "two IPs" which tightly couples it to the stuff further down the page on the recommended DNS config.  I recommend changing some of those DNS config instructions, and if those changes are made that will invalidate this section of the NTP instructions.  So those NTP instructions will also need to be updated accordingly, and ideally are updated in such a way that they aren't so specific about what is documented further below.
* Instead of recommending [these two IPs](https://github.com/pivotal-cf/docs-pcf-install/blob/2a86a6a6e43e9b5ea1476ace1aa82bc775611ab5/gcp-om-config.html.md.erb#L140-L141) we could simply recommend the `.1` IP (it's the same IP we recommend for Gateway) since GCP happens to run a DNS server there, which will be accessible from all VMs and should be reachable from all app containers as well...
* ... If someone will set up networking rules for apps (today implemented via Application Security Groups) to block traffic from the app to the `.1` IP, we can advise users to either (a) enable BOSH DNS (possible in PCF 2.0 only), or (b) configure PAS to pass a different DNS server value to containers, using something like `8.8.8.8` or the GCP metadata IP (`169.254.169.254`), whatever they expect to be reachable from their app containers given their ASGs.  I'm not sure where the feature (b) is documented, it's an optional config somewhere within PAS.
* All the subsequent tables in this doc should be updated accordingly
* I have not checked whether other doc pages make reference to this page and make assumptions about how DNS has been set up.

/cc @jbayer @dsboulder

**Comment by mlimonczenko** [comment]
Thank you, @Amit-PivotalLabs!
