### ISSUE TITLE
Configure Ops Manager Step 4 results in an error

### ISSUE THREAD

**Issue by hijglander** [pivotal-cf/docs-pcf-install#266]
Issue:
Step 4: Create Networks Page
When performing all steps like in the documentation (Add all networks and then press "Save") results in an error saying to contact Pivotal Support. (Ops Manager v1.12.5 on Azure).

Solution:
However pressing "Save" after adding each network results in a succesful adding of all networks.

Please add "Press Save" after each network in the documentation.

**Comment by mlimonczenko** [comment]
Thank you, @hijglander!
