### ISSUE TITLE
diego architecture link requires login to access

### ISSUE THREAD

**Issue by DennisDenuto** [pivotal-cf/docs-pcf-install#283]
The link to https://docs.pivotal.io/pivotalcf/2-0/concepts/diego/diego-architecture.html#diagram requires a login to access. Is this expected behavior?

See: https://github.com/pivotal-cf/docs-pcf-install/blob/1.12/config_firewall.html.md.erb#L17

**Comment by seviet** [comment]
Thanks for reporting this, @DennisDenuto! I've made the link relative.
