### ISSUE TITLE
Dont see AWS terraform file from PAS products

### ISSUE THREAD

**Issue by PavanDevops** [pivotal-cf/docs-pcf-install#284]
Dont see AWS terraform file to download from PAS products list.

Refer : https://github.com/pivotal-cf/docs-pcf-install/blob/master/aws-prepare-env-terraform.html.md.erb

```
Navigate to the Pivotal Application Service (PAS) release on Pivotal Network.
Download the AWS Terraform zip file. 
```

Can only see GCP terraform file.

Please recheck.

**Comment by ljarzynski** [comment]
@PavanDevops I contacted the team responsible for uploading this file. Please check again. It should be there now.

**Comment by PavanDevops** [comment]
@ljarzynski Awesome, I got it. Thank you.
