### ISSUE TITLE
Broken link for NSX-T tile install

### ISSUE THREAD

**Issue by RamXX** [pivotal-cf/docs-pcf-install#285]
Under **[(Optional) Step 3: Install the NSX-T Tile](https://docs.pivotal.io/pivotalcf/2-0/customizing/vsphere.html#nsx-t)** , the [referenced link](https://s3.amazonaws.com/prod.tracker2/resource/85792716/nsxt_21_ncp_kubernetes-1127.pdf) is broken.

**Comment by seviet** [comment]
Thank you for reporting this! We've updated the link.

**Comment by RamXX** [comment]
Verified. Thank you!
