### ISSUE TITLE
AWS instance requirements are outdated

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-pcf-install#297]
The required numbers and types of EC2 instances in AWS Requirements are outdated:
https://github.com/pivotal-cf/docs-pcf-install/blob/2.0/aws.html.md.erb#L21

A default deployment has following instances:

Opsman | 1 | m4.large
BOSH | 1 | m4.large
Consul | 3 | t2.micro
NATS | 2 | t2.micro
File Storage | 1 | m4.large
MySQL Proxy | 2 | t2.micro
MySQL Server | 3 | r4.large
Backup Prepare Node | 1 | t2.micro
Diego BBS | 3 | t2.micro
UAA | 2 | m4.large
Cloud Controller | 2 | m4.large
Router | 3 | t2.micro
MySQL Monitor | 1 | t2.micro
Clock Global | 1 | t2.micro
Cloud Controller Worker | 2 | t2.micro
Diego Brain | 3 | t2.small
Diego Cell | 3 | r4.xlarge
Loggregator | 3 | t2.micro
Syslog Adapter | 3 | t2.micro
Syslog Scheduler | 1 | t2.micro
Doppler | 3 | t2.micro
Errands |   | t2.small
Errands |   | t2.micro

**Comment by ljarzynski** [comment]
Thanks for letting us know @vchrisb! I went ahead and deployed PCF on AWS using Terraform to confirm, and made this commit to update the instance counts: https://github.com/pivotal-cf/docs-pcf-install/commit/b0a4fa85fe33503c965b0976dd450085dbea42f8. 

I also added a note that our numbers assume you are using external DB and file storage, which means we can get rid of the file storage and mysql/backup vms.
