### ISSUE TITLE
Scale Down and Disable Resources outdated

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-pcf-install#298]
`Cloud Controller Database` and `UAA Database` are not available anymore for `Step 23: (Optional) Scale Down and Disable Resources`
https://docs.pivotal.io/pivotalcf/2-0/customizing/aws-er-config-terraform.html#disable-resources

https://github.com/pivotal-cf/docs-pcf-install/blob/2.0/aws-er-config-terraform.html.md.erb

**Comment by kdolor-pivotal** [comment]
Hi @vchrisb 

Is this change applicable to 2.0+ only?

**Comment by vchrisb** [comment]
no this is not only applicable to 2.0
I don't have the history how and when this changed.

**Comment by ljarzynski** [comment]
@vchrisb Thanks for filing this issue! I've updated versions 1.9-2.0 with correct lists of VMs you can scale down depending on your configuration. These updates will appear on our site the next time we do a prod push (usually once per day)
