### ISSUE TITLE
Terraform instructions and PivNet location

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/docs-pcf-install#302]
I find the docs confusing at 
https://github.com/pivotal-cf/docs-pcf-install/blob/cce7e43561e38acd1c63770e67504bf4868f16fd/gcp-prepare-env-terraform.html.md.erb

The instructions of infra paving are for OpsManager and GCP
This is common for OpsManager, service tiles, PAS, and PKS

But then the terraform release is refered to to be available in PivNet / PAS section
The link is not direct but just go to the PivNet homepage

and if I my goal is to install OpsManager + PKS (not PAS) - then I end up lost a bit.

imho the Terraform infra paving for both GCP and AWS should be released in PivNet / OpsManager

and then the doc should be ideally pointing to the exact sub category page and not just PivNet home page.

**Comment by apeek4** [comment]
Hi @avasseur-pivotal ! We modified the docs to clarify the procedure in question. Thank you for your feedback.

Unfortunately, the docs team is not in control of which IaaSes have terraform scripts listed on PivNet. We'll forward your request to the appropriate team. Thanks!
