### ISSUE TITLE
Type: Should be "ec2:DescribeAvailabilityZones",

### ISSUE THREAD

**Issue by mcnichol** [pivotal-cf/docs-pcf-install#306]
https://github.com/pivotal-cf/docs-pcf-install/blob/d6e1447b32d18ff816e04a078b66cbe0f9ff24ba/policy-doc.html.md.erb#L33

Oh the irony: Title should be **Typo**

**Comment by animatedmax** [comment]
Hi @mcnichol This should now be correct in the v1.10, v1.11, v1.12, and v2.0 versions of the documentation. Thanks for pointing it out!
