### ISSUE TITLE
Bosh VM not able to communicate with Ops Manager

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#311]
I'm using Cloud Formation template for v1.12 and following the docs. 
The Ops Manager setup fails, following is the snippet from logs - 
Started deploying
  Waiting for the agent on VM 'i-0ecceafadf18e65c2'... Failed (00:00:30)
  Deleting VM 'i-0ecceafadf18e65c2'... Finished (00:00:35)
  Creating VM for instance 'bosh/0' from stemcell 'ami-cfcbfdb5 light'... Finished (00:00:26)
  **_Waiting for the agent on VM 'i-01fd408e71c9cd351' to be ready... Failed (00:11:12)
Failed deploying (00:12:50)_**

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  **_Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://vcap:<redacted>@10.x.x.x:pppp/agent: dial tcp 10.x.x.x:pppp: i/o timeout
Exit code 1
===== 2018-02-05 07:36:17 UTC Finished "bosh2 --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"; Duration: 776s; Exit Status: 1
Exited with 1._**

We did following to resolve this issue -
1. Go to AWS, find out that BOSH VM is running
2. Get the Sec Group for BOSH and Ops Manager VMs, both should be in the same security group.
3. Modify the security group to allow inbound TCP and UDP traffic from all ports and use the security group where BOSH and Ops Manager are running. 

There is no way to find out this solution is required (except helpful colleagues) as the high level review of the security group shows that TCP ports 80, 22, 443 are open from all sources (0.0.0.0/0). And if the UDP is required then the Cloud Formation template has bugs. 
Either way Docs and Cloud Formation template both need to be updated.

**Comment by seviet** [comment]
hi @msathe-tech. I'm going to recommend that you file this issue in the https://github.com/pivotal-cf/cloudforming-aws repo and/or the #cf-infrastructure Slack channel. we can then follow up with the team that maintains theses templates for any related doc updates. closing. cc:/@evanfarrar
