### ISSUE TITLE
AWS AMI ID for US-EAST-2 not available in Cloud Formation template

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#312]
I see following entries in 1.12 template - 
  "Description": "CloudFormation template for configuring Pivotal Cloud Foundry on AWS",
  "Mappings": {
    "NATRegionToAmiMap" : {
      "us-east-1" : {
        "id" : "ami-303b1458"
      },
      "us-west-1" : {
        "id" : "ami-7da94839"
      },
      "us-west-2" : {
        "id" : "ami-69ae8259"
      },
      "eu-west-1" : {
        "id" : "ami-6975eb1e"
      },
      "eu-central-1" : {
        "id" : "ami-46073a5b"
      },
      "ap-southeast-1" : {
        "id" : "ami-b49dace6"
      },
      "ap-northeast-1" : {
        "id" : "ami-03cf3903"
      },
      "ap-southeast-2" : {
        "id" : "ami-e7ee9edd"
      },
      "sa-east-1" : {
        "id" : "ami-fbfa41e6"
      }
    }
  },

**Comment by seviet** [comment]
hi @msathe-tech! Again, I'm going to recommend reporting this issue against the https://github.com/pivotal-cf/cloudforming-aws repo. The docs team does not maintain the CloudFormation template. If you need more help, try the #cf-infrastructure Slack channel.
