### ISSUE TITLE
Pivotal ERT smoke test fails to connect with api.sys. 

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#313]
I added following domains for creating certificates in ERT:
*.mydomain, *.apps.mydomain, *.sys.mydomain, *.api.sys.mydomain, *.login.sys.mydomain, *.uaa.sys.mydomain

Getting following error in smoke test - 
[32m[2018-02-06 00:51:57.92 (UTC)]> cf api https://api.sys.<mydomain>[0m  
           Setting api endpoint to [36;1mhttps://api.sys.mydomain[0m...  
           SSL Certificate Error x509: certificate is valid for *.mydomain, not api.sys.mydomain  
           TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint  
           [31;1mFAILED[0m  
           [91m[1mFailure [0.294 seconds][0m  
           [91m[1m[AfterSuite] AfterSuite [0m  
           [37m/var/vcap/packages/smoke_tests/src/github.com/cloudfoundry/cf-smoke-tests/smoke/etcd_cluster_check/init_test.go:52[0m  
             
             [91mNo future change is possible.  Bailing out early after 0.132s.  
             Expected  
                 <int>: 1  
             to match exit code:  
                 <int>: 0[0m

**Comment by msathe-tech** [comment]
Should have mentioned, I’m using v1.12 with Cloud Formation on AWS

**Comment by msathe-tech** [comment]
I was able to setup successfully twice with the same certificates. So it’s really strange that it is failing now.

**Comment by seviet** [comment]
Hi @msathe-tech. I'm sorry you're having difficulties with your deployment! Again, I would ask for help on either the #pcf-releng or #platform-architecture Slack channels and then if you do find a specific doc content issue that we can fix to make the experience better for the next person, please do come back and let us know. Thanks!
