### ISSUE TITLE
GCP prereq docs - roles not found as per the docs

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#318]
I'm referring to docs - https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-prepare-env.html

It lists the roles to be assigned to the service accounts. What I see on the GCP don't match to what is in the docs. 

<img width="528" alt="screen shot 2018-02-10 at 5 57 42 pm" src="https://user-images.githubusercontent.com/32221454/36067470-0118a1fc-0e8c-11e8-8778-3b2891d53a4e.png">

**Comment by mlimonczenko** [comment]
Hello, @msathe-tech. Could you tell me what about the two screenshots are different?
