### ISSUE TITLE
2.1 config credhub step 10

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pcf-install#331]
the screen shot in step 10 is missing HSM configuration as well as the steps.  This is a mandatory config in opsman
https://github.com/pivotal-cf/docs-pcf-install/blob/master/config-er-vmware.html.md.erb#L182

**Comment by seviet** [comment]
Fixed with delivery of https://www.pivotaltracker.com/story/show/154376071. Thanks @randomtask1155!
