### ISSUE TITLE
step 9 configuring UAA should explain why we need a cert

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pcf-install#332]
We should explain to the ready why we need to add a certificate in cases where a user does not plan to use and external SAML SP 

https://github.com/pivotal-cf/docs-pcf-install/blob/master/config-er-vmware.html.md.erb#L178

**Comment by mlimonczenko** [comment]
Hello @randomtask1155,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
