### ISSUE TITLE
Step 6 entering the certificate body when using AWS certificate manager.

### ISSUE THREAD

**Issue by bmeers** [pivotal-cf/docs-pcf-install#333]
When using AWS certificate manager you are not give the .pem format key.   This is not easily obtained from AWS certificate manager and it appears that I can not validate my cert without an associated A record.  The opsmanager is not created until the Terraform script is ran so how would I know the IP for the A record.   It was be nice if the documentation was more clear or used a Terraform module that can accept the ARN of the certificate like the Cloudformation template.

**Comment by mlimonczenko** [comment]
Hello @bmeers ,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
