### ISSUE TITLE
Received Ruby error stack when using wrong URL in Opsmanager setup.

### ISSUE THREAD

**Issue by bmeers** [pivotal-cf/docs-pcf-install#334]
When setting up the PCF url in the Opsmanager UI I put in the wrong address and instead of a legible error message we received a ruby stack.

**Comment by mlimonczenko** [comment]
Hello @bmeers,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
