### ISSUE TITLE
Change Screenshots from C# to Flash or HTML5 client

### ISSUE THREAD

**Issue by tschwaller** [pivotal-cf/docs-pcf-install#343]
In `deploying-vm.html.md.erb`screenshots using the C# client are used. They should be changed to screenshots using the Flash or even better the HTML5 client, since vSphere 6.7 (in Q2 2018) will be the last version supporting Flash. Time for a change!

**Comment by pspinrad** [comment]
Hey @tschwaller -- updating those images would be great.  If you can send replacement screenshots for these, I will swap them in:

https://docs.pivotal.io/pivotalcf/2-4/om/common/images/vms-templates.png
https://docs.pivotal.io/pivotalcf/2-4/om/common/images/new-folder.png
https://docs.pivotal.io/pivotalcf/2-4/om/common/images/ova.png

I don't have a VMware environment handy.  Thank you, and apologies for delayed reply!

**Comment by mlimonczenko** [comment]
Hello @tschwaller,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
