### ISSUE TITLE
Missing step to create SSH key used in VPC creation

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#367]
Ref: [https://docs.pivotal.io/pivotalcf/2-0/customizing/pcf-aws-manual-config.html](https://docs.pivotal.io/pivotalcf/2-0/customizing/pcf-aws-manual-config.html)

While following the document to create PCF on AWS, I struggled to understand which key is being referred with name "pcf-ops-manager-key" in VPC creation step 4. I rescanned the document several times but could not find any step where I was instructed to create an SSH key with such a name before. 

Though I have figured out the issue now but updating this document with this missing step will certainly help others.

**Comment by mlimonczenko** [comment]
Thank you so much, @parth-pandit. We've revised the topic.
