### ISSUE TITLE
Request for improved instructions for S3 bucket creation

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#369]
Ref: [https://docs.pivotal.io/pivotalcf/2-0/customizing/pcf-aws-manual-config.html](https://docs.pivotal.io/pivotalcf/2-0/customizing/pcf-aws-manual-config.html)

While referring to this document to create S3 buckets for my PCF setup, I have observed that S3 will not take duplicate bucket names. So, the instructions should be updated to accommodate this restriction and guide the user for a better unique bucket naming conventions.

Additionally, because of the unique bucket name requirements, the IAM policy will not be applicable as is and the user may need to change the bucket names accordingly to assign permissions. The document should also have the reference to it in the instructions of IAM policy attachment steps.

**Comment by mlimonczenko** [comment]
Hello @parth-pandit ,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
