### ISSUE TITLE
CredHub Encryption Provider steps missing

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#394]
The guide to install PCF on AWS using Terraform is missing steps to configure CredHub Encryption Provider on Director Config line item.

**Comment by mjgutermuth** [comment]
Hi @parth-pandit! Can you let us know which version the guide you're looking at?

The step to configure the **CredHub Encryption Provider** field appears in the PCF 2.1 docs here: https://docs.pivotal.io/pivotalcf/2-1/customizing/aws-om-config-terraform.html#director-config
