### ISSUE TITLE
Resource Configuration missing ELB instructions

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#396]
The page at below link should have some instruction on what needs to be done for the "Load Balancers" input boxes under "Resource Configuration" page of Ops Manager tile configuration.
https://docs.pivotal.io/pivotalcf/2-0/customizing/aws-om-config-terraform.html

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
