### ISSUE TITLE
PAS Tile Needs New Image

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#397]
The PAS tile image is of ERT, which is very old. Please replace it with the new image file for PAS with a new logo and look to avoid any confusion.

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
