### ISSUE TITLE
Missing instruction on Application Developer Controls

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#399]
There is no instruction for the option with name "Enable Service Discovery for Apps" on Application Developer Controls options of PAS tile configuration. Though, this is self explanatory it should be there.

**Comment by mlimonczenko** [comment]
Hello @parth-pandit ,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
