### ISSUE TITLE
PAS tile configuration head is missing

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#400]
The configuration step with heading "Authentication and Enterprise SSO" is wrongly sequenced. The document directly jumps on the "UAA" step and then cover "Authentication and Enterprise SSO", which is not in line with PAS tile steps.

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
