### ISSUE TITLE
No Diago Cell in Resource Config

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-pcf-install#401]
The instructions under heading **Diego Cell Memory and Disk Overcommit** says to check the memory and disk configurations available in **Resource Config** option for Diago Cell. However, the **Resource Config** screen does not have any row for Diago Cell. Also, the configuration sequence should be changed if the user has to take reference from the future step of configuration.

**Comment by seviet** [comment]
hi @parth-pandit -- could you point us (link) to the exact doc topic that you are looking at?

**Comment by mlimonczenko** [comment]
Hello @parth-pandit,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
