### ISSUE TITLE
GCP PAS tile documentation not clear about LB setup

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#406]
I used terraform to setup IaaS.
The docs here - https://docs.pivotal.io/pivotalcf/2-1/customizing/gcp-er-config.html#config-lb
doesn't refer to the output of the terraform for setting up the LBs. 
It is very difficult to follow the instructions when the docs doesn't refer to the previous setup steps.

**Comment by mlimonczenko** [comment]
Hello @msathe-tech,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
