### ISSUE TITLE
Docs don't mention GIT location for terraforming GCP 

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#407]
Im referring to the docs here - https://docs.pivotal.io/pivotalcf/2-1/customizing/gcp-prepare-env-terraform.html

The docs doesn't mention the actual GIT location for terraform. I used https://github.com/pivotal-cf/terraforming-gcp in absence of any guidance on the docs. Now the trouble is, the git terraform uses different subnet settings that the docs. And this has messed up my installation.

**Comment by seviet** [comment]
@msathe-tech Sorry you had this difficulty! But yes, hopefully you noticed that we instruct the user to download the released terraform templates from Pivotal Network, not Github. See https://docs.pivotal.io/pivotalcf/2-1/customizing/gcp-prepare-env-terraform.html#download
