### ISSUE TITLE
Subnet mismatch between terraform and docs for PCF on GCP

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#408]
https://docs.pivotal.io/pivotalcf/2-1/customizing/gcp-om-config-terraform.html

This docs refer to the networks starting with 192.168.x.x 
However the same docs provide GCP terraform (downloaded from pivnet) and that has networks starting from 10.0.x.x 

This is confusing and causing installation issues in GCP.

**Comment by seviet** [comment]
hi @msathe-tech! i am so sorry you're having difficulties with your GCP installation. I'm looking over the Terraform templates available on PivNet, but I do not see any references to 10.0.x.x networks in them. @evanfarrar can you comment on whether we have a mismatch between our doc examples and the current Terraform scripts?

**Comment by mlimonczenko** [comment]
Hello @msathe-tech,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
