### ISSUE TITLE
The subnet sizes created for the PCF management network by terraform are too small

### ISSUE THREAD

**Issue by scarolan** [pivotal-cf/docs-pcf-install#412]
The terraform.zip file you provided creates three tiny management subnets with only ten IP addresses free in each.  This causes Pivotal Application Service to fail because it needs more IP addresses to complete the installation.  Here is the fix, with the small subnets commented out:

```
locals {
  public_cidr     = "${cidrsubnet(var.vpc_cidr, 6, 0)}"
  #management_cidr = "${cidrsubnet(var.vpc_cidr, 10, 64)}"
  pas_cidr        = "${cidrsubnet(var.vpc_cidr, 6, 1)}"
  services_cidr   = "${cidrsubnet(var.vpc_cidr, 6, 2)}"
  rds_cidr        = "${cidrsubnet(var.vpc_cidr, 6, 3)}"
  management_cidr = "${cidrsubnet(var.vpc_cidr, 6, 4)}"
}
```

**Comment by mlimonczenko** [comment]
Hello @scarolan,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
