### ISSUE TITLE
Security group in the ops_manager module is too restrictive

### ISSUE THREAD

**Issue by scarolan** [pivotal-cf/docs-pcf-install#413]
BOSH installation failed with timeouts until I added this to allow local traffic among subnets.  It looks like you had the same issue with CloudFormation templates:

https://github.com/pivotal-cf/docs-pcf-install/issues/311

```
  ingress {
    cidr_blocks = ["10.0.0.0/16"]
    protocol    = "tcp"
    from_port   = 0
    to_port     = 65535
  }
```

**Comment by mlimonczenko** [comment]
Hello @scarolan,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
