### ISSUE TITLE
mysql recovery guid reference to mariadb_ctrl no longer exists in 2.2

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pcf-install#432]
**URL or GitHub link to the page where you're having the issue**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

https://github.com/pivotal-cf/docs-pcf-install/blob/18fb98577000089b4395b6bc108cf8155f80771f/mysql_bootstrap_ert.html.md.erb#L192

https://github.com/pivotal-cf/docs-pcf-install/blob/18fb98577000089b4395b6bc108cf8155f80771f/mysql_bootstrap_ert.html.md.erb#L222

https://github.com/pivotal-cf/docs-pcf-install/blob/18fb98577000089b4395b6bc108cf8155f80771f/mysql_bootstrap_ert.html.md.erb#L236

**Is your request for a change or addition to content related to a problem? If so, please describe.**
A clear and concise description of the problem. For example: "Whenever I upgrade my software I forget to first collect information about the things I've already installed"

The `mariadb_ctl` service no longer exists in this release which will impact how a user can troubleshooting the internal database instances.

**Describe the solution you'd like**

correct the command references 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or content you've considered.

**Additional context**
Add any other context or screenshots about the content request here.

**Comment by menicosia** [comment]
MySQL team story [#158671057](https://www.pivotaltracker.com/story/show/158671057)

**Comment by ljarzynski** [comment]
@randomtask1155 Thanks for making this issue. The MySQL team submitted a PR to the documentation, which has been merged (see: https://github.com/pivotal-cf/docs-pcf-install/pull/442). Those updates will be on the site shortly if not already. I'm closing out this PR but please feel free to reopen or reach out if any additional questions/concers.
