### ISSUE TITLE
replication-canary job failed from mysql-monitor release

### ISSUE THREAD

**Issue by masalinas** [pivotal-cf/docs-pcf-install#445]
Installing tha last Pivotal Product **PAS Small Footprint** version 2.2.0 using **Terraform** on **GPC** I obtained this error using **MySQL internally**

`L Error: 'mysql_monitor/cd0378d1-2920-4e4b-99c5-37ffce2101b0 (0)' is not running after update. Review logs for failed jobs: replication-canary`

And these logs from replication-canary logs:

```
goroutine 1 [running]:
replication-canary/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc42005a240, 0x79be22, 0x1d, 0x7d4de0, 0xc4201d5020, 0x0, 0x0, 0x0)
	/var/vcap/packages/replication-canary/src/replication-canary/vendor/code.cloudfoundry.org/lager/logger.go:152 +0x4d2
main.main()
	/var/vcap/packages/replication-canary/src/replication-canary/main.go:99 +0x1803
panic: Post https://uaa.sys.training.konetika.net/oauth/token: x509: certificate is valid for training.konetika.net, not uaa.sys.training.konetika.net
```

I saw some points to be checked and possible resolve the problem;

1. Make sure you have selected the **Forward SSL to PAS Router** option in your [PAS Network Configuration](gcp-er-config.html#networking).

   This option not exist from product **PAS Small Footprint** inside Ops Manager Networking Configuration view.

1. Verify that you have configured the firewall rules properly and that TCP ports `80`, `443`, `2222`, and `8080` are accessible on your GCP load balancers. See [Create Firewall Rules for the Network](./gcp-prepare-env.html#firewall_rules). 
  
    Is correct

1. Verify that you have configured the proper SSL certificates on your [HTTP(S) load balancer in GCP](./gcp-prepare-env.html#create-http-and-instance-group). 

   I used the PAS self-signed certificate tool to create the private a SSL certificate using these domain targets from networking Ops Manager view:
   *.apps.training.konetika.net, *.sys.training.konetika.net, *.uaa.sys.training.konetika.net, *.login.sys.training.konetika.net, *.training.konetika.net

   The certificated created previously was pasted in the SSL Proxy used in my HTTP(S) Load balancer in GCP

1. If necessary, re-upload a new certificate and update any required SSL Certificate and SSH Key fields in your [PAS network configuration](./gcp-er-config.html#). 

But I don't understand what I must to do!!. I always obtain the previous error !

How I could resolve this problem?

**Comment by pspinrad** [comment]
Thank you for raising this issue, and I'm sorry that you are having trouble. Please sign in to [Pivotal Support](https://support.pivotal.io) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.

Meanwhile, I'll look into your point that the **Forward SSL to PAS Router** option doesn't exist in PAS Small Footprint config, which seems like a clear documentation problem-- thanks for pointing it out!  Pivotal Support can investigate your specific situation, and we'll work with them to update the documentation for any general problems that we learn about.

**Comment by masalinas** [comment]
Today I just terminate install Pivotal on GPC. I resolved the problem unchecking the SSL validation on network configuration and configuring the load balancers on the resource configuration view (some mistaked from me). 

I don't know why if I stop the VMs from PAS and then restart it some VMs like control, mysql-monitor, etc are on warned status, because some jobs not restart.

Also the check to disable for example the replication-canary jod not exist from PAS Small Footprint also.

Regards

**Comment by HoffiMuc** [comment]
If you are not using SSL encryption or if you are using self-signed certificates, select/tick _"Disable SSL certificate verification for this environment"_ in PAS tile networks configuration: "
Selecting this checkbox also disables SSL verification for route services.

Note: For production deployments, Pivotal does not recommend disabling SSL certificate verification.
