### ISSUE TITLE
Configuring BOSH Director on GCP - Step #5 - Needs additional checkbox for services network

### ISSUE THREAD

**Issue by dashaun** [pivotal-cf/docs-pcf-install#448]
https://docs.pivotal.io/pivotalcf/2-2/customizing/gcp-om-config.html#network

For "PAS AND OTHER RUNTIMES"

For Network Name - services-1

None of the table references the "Service Network" checkbox.  So I assumed that all three networks would stay unchecked.

I'm using v2.0-build.335 and the installation fails unless I check the box for the services-1 network.  I left it unchecked for infrastructure and pas.

I would like to see that called out as a difference from the other 2 networks.

If this checkbox was identified in the documentation I would have more confidence in my solution.

<img width="1672" alt="screen shot 2018-07-18 at 4 05 06 pm" src="https://user-images.githubusercontent.com/826271/42907775-73c9bb48-8aa4-11e8-8f64-bb41e6802130.png">

**Comment by pspinrad** [comment]
@dashaun if you're using v2.0-build.335, try the v2.0 version of the docs https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-om-config.html#network which gives different instructions for `services-1`:

> Google Network Name | 
> Enter the name of the services network you created when preparing your GCP environment.The format is: MY-PCF-virt-net/MY-PCF-subnet-services-MY-REGION/MY-GCP-REGION
