### ISSUE TITLE
How do I configure a Jumpbox for BBR?

### ISSUE THREAD

**Issue by tnwang** [pivotal-cf/docs-pcf-install#455]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-1/customizing/backup-restore/system-setup-bbr.html#jumpbox

**Is your request for a change or addition to content related to a problem? If so, please describe.**
I don't know what to do based on the instructions provided. Is there some other documentation that I should be referring to in order to set up a jumpbox? Do I already have a jumpbox that OpsManager gave me? This is very unclear.

**Describe the solution you'd like**
Either actual steps or links to actual steps to set up or get access to a jumpbox.

**Describe alternatives you've considered**
A quick Google search turned up nothing. I did ask OpsManager and they said you could maybe use the OpsManager VM as a jumpbox but there are caveats that it might not talk to all VMs so I'm also unclear whether it would work for BBR.

**Additional context**
I'm doing troubleshooting for an issue a customer saw running BBR, and noticed this while trying to run BBR myself the way our customers would.

**Comment by bentarnoff** [comment]
Hey @tnwang thanks so much for raising the issue.

As of PCF v2.5, the Ops Manager VM will include the BBR binary. As a result, we've updated the PCF v2.5 documentation to recommend that users use the OM VM as their BBR jumpbox. If users want to use a custom jumpbox, however, we've also linked out to a new Knowledge Base article that explains how to do that.

For more information about our updates, please see the acceptance note in the corresponding [story](https://www.pivotaltracker.com/story/show/159179465). And thanks again!
