### ISSUE TITLE
ops_manager_image_url should be ops_manager_image_uri in terraform.tfvars

### ISSUE THREAD

**Issue by jimbasler-pivotal** [pivotal-cf/docs-pcf-install#457]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-2/customizing/azure-deploy-terraform.html in "Step 1: Download and Edit the Terraform Variables File", see step 7 in that section.

**Is your request for a change or addition to content related to a problem? If so, please describe.**
When applying the plan you are prompted for the ops_manager_image_ui because it is not being found in terraform.tfvars because the key name is incorrect. It is using "...url" instead of "...uri" with an "i".

**Describe the solution you'd like**
Update the doc.

**Describe alternatives you've considered**
The workaround is to just enter it again at the command prompt.

**Additional context**
![image](https://user-images.githubusercontent.com/10993779/43157103-9bac7dc0-8f41-11e8-9cdb-d846204fa1c8.png)

**Comment by pspinrad** [comment]
Thanks @jimbasler-pivotal - fixed - building to docs staging site now, will send you pointer.
