### ISSUE TITLE
Scale down PAS docs incorrectly instructs users of external databases to disable backup prepare node

### ISSUE THREAD

**Issue by MirahImage** [pivotal-cf/docs-pcf-install#470]
**URL or GitHub link to the page where you're having the issue**
Example of a live page in PCF 2.2 docs: https://docs.pivotal.io/pivotalcf/2-2/customizing/gcp-er-config-terraform.html#disable-resources

Partials used:
- https://github.com/pivotal-cf/docs-pcf-install/blob/334e26484095f1e6669cab948bc044fce3defc7c/_disable_resources.html.md.erb#L25
- https://github.com/pivotal-cf/docs-pcf-install/blob/334e26484095f1e6669cab948bc044fce3defc7c/_disable_resources_azure.html.md.erb#L25

Versions: master, 2.2, 2.1, 2.0, 1.12, 1.11

**Is your request for a change or addition to content related to a problem? If so, please describe.**
The Backup Prepare node is required for backup and restore using BBR for PCF 1.11 and later. Therefore, scaling down the Backup Prepare node is not part of scaling down when I choose an external database.

**Describe the solution you'd like**
Change the docs so that scaling down the Backup Prepare node is a separate choice from scaling down the internal database.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Mirah and @jamesjoshuahill

**Comment by bentarnoff** [comment]
Thanks @MirahImage. This issue appears to have been resolved, so I'm closing it.
