### ISSUE TITLE
PCF deployment issue

### ISSUE THREAD

**Issue by vchattamoni** [pivotal-cf/docs-pcf-install#472]
Hello,

I am receiving below error while configuring BOSH Director on Vsphere.

===== 2018-07-30 16:56:37 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'

Started validating
  Validating release 'bosh'... Finished (00:00:01)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating release 'uaa'... Finished (00:00:02)
  Validating release 'credhub'... Finished (00:00:02)
  Validating release 'bosh-system-metrics-server'... Finished (00:00:03)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating release 'backup-and-restore-sdk'... Finished (00:00:07)
  Validating release 'bpm'... Finished (00:00:03)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:05)
Finished validating (00:00:28)

Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:00:00)
  Compiling package 'vsphere_cpi/e1a84e5bd82eb1abfe9088a2d547e2cecf6cf315'... Finished (00:00:00)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:00)
  Installing packages... Finished (00:00:08)
  Rendering job templates... Finished (00:00:03)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:11)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.25'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'vm-63ba51a2-d2cc-4b88-8e3c-caa0333b0a05'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Deleting VM 'vm-63ba51a2-d2cc-4b88-8e3c-caa0333b0a05'... Finished (00:00:15)
  Creating VM for instance 'bosh/0' from stemcell 'sc-34b10785-66e3-4859-b0aa-03aec2b12ad2'... Finished (00:00:32)
  Waiting for the agent on VM 'vm-069a64af-3980-4794-b6e7-9c2d23ed7c2b' to be ready... Finished (00:00:26)
  Creating disk... Failed (00:00:09)
Failed deploying (00:01:37)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Updating instance disks:
      Updating disks:
        Deploying disk:
          Creating disk with size 51200, cloudProperties property.Map{"type":"thin"}, instanceID vm-069a64af-3980-4794-b6e7-9c2d23ed7c2b:
            CPI 'create_disk' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"No valid placement found for disks:\n- Size: 51200, Target DS Pattern: ^(Datastore2)$, Current Location: N/A\n\nPossible placement options:\nDatastores:\n  - Name: Datastore1, free space: 922197\n","ok_to_retry":false}

Exit code 1
===== 2018-07-30 16:58:56 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"; Duration: 138s; Exit Status: 1
Exited with 1.

__________________________________________________________

Any Idea what is causing the issue?

Thanks in Advance.

Regards,
Vamshi Chattamoni

**Comment by musmankhan88** [comment]
Hello,

           I am facing an error while deploying PCF PAS 2.2 manifest tile. 

Task 177 | 20:06:35 | Preparing deployment: Preparing deployment (00:00:04)
                    L Error: Colocated job 'bosh-dns-aliases' is already added to the instance group 'database'.
Task 177 | 20:06:39 | Error: Colocated job 'bosh-dns-aliases' is already added to the instance group 'database'.

Task 177 Started  Tue Jul 31 20:06:35 UTC 2018
Task 177 Finished Tue Jul 31 20:06:39 UTC 2018
Task 177 Duration 00:00:04
Task 177 error

**Comment by musmankhan88** [comment]
I am deploying on AWS

**Comment by vchattamoni** [comment]
I am currently at the beginning stage of installation, I have come across a link where it stated that DNS aliases will not work with pcf 2.2

**Comment by mlimonczenko** [comment]
Hello @vchattamoni,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
