### ISSUE TITLE
in Step 6: Create Database Instance and Databases, get a more clear explanation to  "Configure machine type and storage: Select db-n1-standard-2". / go to Configuration options , then ... 

### ISSUE THREAD

**Issue by dburkhalter-pivotal** [pivotal-cf/docs-pcf-install#477]
**Describe the bug**
A clear and concise description of the bug. For example: "The PCF v2.0 Release Notes are missing the new Cookie feature."

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS, Browser, and Version:**

**Additional context**
Add any other context about the problem.

**Comment by pspinrad** [comment]
@dburkhalter-pivotal the missing info is, you click **Change** under **Configure machine type and storage** -- and _then_ you can select `db-n1-standard-2`.  Added that step to the docs.
