### ISSUE TITLE
Removal of the PCF Azure Resource Manager Template

### ISSUE THREAD

**Issue by mxplusb** [pivotal-cf/docs-pcf-install#479]
**URL or GitHub link to the page where you're having the issue**

Pivotal Cloud Foundry Installation Guide

**Is your request for a change or addition to content related to a problem? If so, please describe.**

The [PCF ARM](https://github.com/pivotal-cf/pcf-azure-arm-templates) template is going to be archived permanently with the 2.3 release. It is not currently maintained and there are no plans to maintain in the future as Pivotal is moving towards terraform for the foreseeable future.

**Describe the solution you'd like**

I will create a Pull Request which removes all references to the ARM template in the installation guide. I would like to work with the docs team to make sure this change gets released when the 2.3 docs are released. This change will need to get backported to versions 2.0, 2.1, and 2.2.

**Additional context**

As no group is looking to maintain the templates, it's in the best interest of Pivotal customers to remove the references and project.

//cc @cwsteve2117 @jastev

**Comment by cshollingsworth** [comment]
Hi, @mxplusb -- since the ARM template will be archived starting in 2.3, do the changes to our docs need to be backported at the time of the 2.3 release, or should it be done earlier than that?
