### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by aclevername** [pivotal-cf/docs-pcf-install#481]
**Describe the bug**
Broken links

**To Reproduce**
1. go to https://docs.pivotal.io/pivotalcf/2-2/customizing/gcp-troubleshooting.html#mysql_rep_canary 
1. try clicking on the links in step 3 and 4 under `Solution`.

**Expected behavior**
To go to the desired page

**OS, Browser, and Version:**
 all

**Additional context**
Check links in versions 1.11 - 2.2

**Comment by cshollingsworth** [comment]
Hi, @aclevername -- these links have now been fixed in all versions of our documentation.

Closing this issue.
