### ISSUE TITLE
VMware HA - Detail re: BOSH and VMware HA Interaction

### ISSUE THREAD

**Issue by onefastxpl** [pivotal-cf/docs-pcf-install#489]
**URL or GitHub link to the page where you're having the issue**
In the documentation items are called out about how the Resurrector and VMware HA interact.  For instance which will win in what scenario.   How do the Resurrector and VMware HA not fight in each scenario.  More detail around why the Resurrector may not work in case of a host or AZ failure.  It would seem it would just start it on another host or cluster in Multi AZ Config.

I'm a Dell EMC Cloud Platform Specialist supporting our Pivotal Ready Architecture

**Comment by mlimonczenko** [comment]
Hello, @onefastxpl. We are trying to find the topic you would like expanded.

Is this the topic? https://docs.pivotal.io/pivotalcf/2-3/customizing/resurrector.html

**Comment by ljarzynski** [comment]
@onefastxpl Just a heads up, we pushed a commit to clarify this page based on your feedback. I will close the issue, but feel free to re open or reach out if you have any questions. Thanks!
