### ISSUE TITLE
Confusing line in PCF deploy Opsmanager

### ISSUE THREAD

**Issue by sanhitamukherji** [pivotal-cf/docs-pcf-install#497]
**https://docs.pivotal.io/pivotalcf/2-2/customizing/**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

![screen shot 2018-08-24 at 12 11 20 pm](https://user-images.githubusercontent.com/10056707/44595752-168ce480-a798-11e8-972f-56d1ec9ec1bd.png)
I was reading up on opsmanager and how to deploy it, and as I was going through docs, I thought I could deploy it using a bosh VM I already had set up on our domain, based on this line (screenshot attached above) . But I guess that's not the case, and we just install opsman and use that to install a new instance of bosh. And if that's the case, the line above is misleading. :(

**Comment by ljarzynski** [comment]
Hi @sanhitamukherji. Thank you for creating this issue. I apologize for the confusion from this particular line in the documentation. To avoid such situations in the future, I have made a commit to change the line to more closely resemble how Ops Manager is described on Pivotal Network: https://github.com/pivotal-cf/docs-pcf-install/commit/1c60afc4ef5cf77a44c3d74c42dbe693ef1a1fac. I will be backporting this to previous versions.
