### ISSUE TITLE
Bad markdown formatting in "Preparing to Deploy PCF on GCP"

### ISSUE THREAD

**Issue by animatedmax** [pivotal-cf/docs-pcf-install#507]
**Describe the bug**
Bad markdown formatting. My biggest concern is that this error has been published to our production sites for at least three weeks. What kind of safety net can we put into place so these kinds of things are noticed before they're made available to the world?

**To Reproduce**
1. Browse to each of these:
    - https://docs.pivotal.io/pivotalcf/2-2/customizing/gcp-prepare-env.html#dbs
    - https://docs.pivotal.io/pivotalcf/2-1/customizing/gcp-prepare-env.html#dbs
    - https://docs.pivotal.io/pivotalcf/2-0/customizing/gcp-prepare-env.html#dbs
    - https://docs.pivotal.io/pivotalcf/1-12/customizing/gcp-prepare-env.html#dbs
2. Observe the following text: "Under MySQL, select instance type Second Generation and click Choose \*\*MySQL*."

**Expected behavior**
"Choose \*\*MySQL*" should be in bold with no asterisks

**Comment by pspinrad** [comment]
Thanks @animatedmax !  Safety net should be me, but I failed-- fixing now...
