### ISSUE TITLE
NSX-T Container plugin (NCP) page is older version

### ISSUE THREAD

**Issue by sandyg1** [pivotal-cf/docs-pcf-install#516]
**Describe the bug**
The PAS V2.2 release has screenshot from older plugin for NSX-T Container plugin (NCP) page.
It is missing the: Overlay Transport Zone and Tier-0 Router

**To Reproduce**
1. Go to 'https://docs.pivotal.io/pivotalcf/2-2/customizing/vsphere-nsx-t.html'
2. The screenshot for NCP does not have the 2 fields in the `VMware NSX-T Container Plug-in for PCF` v2.2.1

**Expected behavior**
The fields mentioned above should be displayed and explanation provided in docs.

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/26017563/45364406-0ce0ea80-b5a8-11e8-9142-ec44fd8bedf0.png)

**OS, Browser, and Version:**
All browsers
**Additional context**
Docs need update

**Comment by pspinrad** [comment]
@sandyg1 thanks -- we updated the image a couple weeks ago but neglected to follow up here-- sorry!:
https://docs.pivotal.io/pivotalcf/2-2/customizing/vsphere-nsx-t.html#nsx-t-tile
https://github.com/pivotal-cf/docs-pcf-install/commit/50e41399464aec1b9215254655b956c70e58a643
