### ISSUE TITLE
Undocumented checkbox in Opsman IdP config

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/docs-pcf-install#517]
**Describe the bug**
There is a checkbox in OpsMan 2.2.x that says "Provision an admin client in the Bosh UAA". This does not appear to be documented.

**To Reproduce**
1. Install OpsMan
2. Click on configure IdP
3. Scroll down to the bottom (see screen)

**Expected behavior**
Would like to have docs for this.,

**Screenshots**

<img width="820" alt="screen shot 2018-09-11 at 10 35 05 am" src="https://user-images.githubusercontent.com/1686293/45378185-0196ba80-b5ba-11e8-97f0-dda671a24d96.png">

**Comment by matthewfischer** [comment]
I believe we just need to link to this:

https://docs.pivotal.io/pivotalcf/2-2/customizing/opsmanager-create-bosh-client.html

**Comment by pspinrad** [comment]
Thanks @matthewfischer for pointing this out -- the docs issue is bigger than this.  We don't document the entire Ops Man **Settings** > **Change Authentication Method to SAML** form, not just that one checkbox (good link for that, BTW).  Closing this issue and creating a story to doc that whole form properly.
