### ISSUE TITLE
AWS architecture should require 1 NAT instance per AZ

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/docs-pcf-install#523]
**Describe the bug**

The AWS Install guide only has you setup 1 NAT instance which is a single point of failure and can also get overloaded. The correct architecture will have a NAT per AZ - so 3 NATs are needed. The other 2 NATs would need to be created after the rest of the subnets are created in Step 4.

Longer term the docs should switch to NAT Gateways but pending that, this is still an issue. The good news is that the automation does it right.

**Comment by aegershman** [comment]
Is there any thoughts on when, if at all, there would be interest in switching to advocating for NAT gateways rather than instances?

**Comment by matthewfischer** [comment]
I do know that it is actively being investigated. I think we should always use them,

**Comment by zmb3** [comment]
Agree we should just start recommending NAT gateways instead.

**Comment by mlimonczenko** [comment]
Hello @matthewfischer,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
