### ISSUE TITLE
AWS manual steps refer to assigning an IAM role to the OpsMan VM - don't explain how to create it

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/docs-pcf-install#525]
**URL or GitHub link to the page where you're having the issue**
Step 12 here https://docs.pivotal.io/pivotalcf/2-2/customizing/pcf-aws-manual-config.html#pcfaws-om-ami

an IAM role is referenced - but I don't see anywhere that this role is created. Earlier we create a user, but not a role.  The existing docs only link to some generic information on roles at AWS.

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Need some directions on this role specifically what is needed or a better link if this documenation is already available.

**Comment by pspinrad** [comment]
@matthewfischer yeah, great point-- there is that **Create new IAM Role** link if you don't already have one, but we don't explain what to do. Do you know?  Like, do you create a role to be used by EC2 instances, and attach the `AdministratorAccess` policy, or??  Thanks!

**Comment by matthewfischer** [comment]
@pivotal-abryant should know I think - I can see what the automation does but have not translated that to docs yet due to lack of time

**Comment by mlimonczenko** [comment]
Hello @matthewfischer,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
