### ISSUE TITLE
Incorrect ELB configuration screenshot for Deploy PAS 2.2 on AWS 

### ISSUE THREAD

**Issue by mma-pivotal** [pivotal-cf/docs-pcf-install#540]
**Describe the bug**
The screenshot for ELB configuration in PAS 2.2 on AWS is incorrect.

https://docs.pivotal.io/pivotalcf/2-2/customizing/pcf-aws-manual-er-config.html#config-elb

In this screenshot, it suggests you to config prefix for ELB names like `http:`, `tcp:`. However if you do config such name in resource config page, apply change will fail.

PS: The screenshot for [PAS 2.1](https://docs.pivotal.io/pivotalcf/2-2/customizing/images/resource_config.png) doesn't have the load balancer name at all, so it didn't cause misunderstanding, but I think it's better to have a screenshot with correct load balancer format which makes the overall configuration easier to understand.

**To Reproduce**
1. Go to OPS Manager - PAS tile - Resource Config - For Load Balancers of Router, enter `http:<your_elb_name>`.
2. Click Save.
3. Go back to installation dashboard and apply change.
4. Apply change will fail with the following error:

```
…
Task 51 | 09:03:50 | Creating missing vms: clock_global/8a9b5069-2bda-45db-94e3-d1545a4db655 (0) (00:01:21)
Task 51 | 09:03:50 | Error: Unknown CPI error ‘Unknown’ with message ‘LoadBalancer name cannot contain characters that are not letters, or digits or the dash.’ in ‘create_vm’ CPI method (CPI request ID: ‘cpi-306959’)
```

**Expected behavior**
A clear screenshot without any prefix for Load balancer.

**Additional context**
https://github.com/pivotal-cf/installation/blob/e376a295fcad79c800d0af18e740e8d134bda7fe/web/app/models/deployer/cloud_config/aws_provider.rb#L32

The above link shows that OPS Manager doesn't like any prefix for ELB name, however it does require `alb:` prefix for ALB name.

**Comment by paigecalvert** [comment]
thanks @mma-pivotal! Do you have a correct screenshot you could share or an environment I could use to take a screenshot? In the 2.2 environment I'm using, the Resource Config pane appears to be missing several fields. I imagine this means the missing fields need to be configured somewhere else before they'll show up here?

<img width="1552" alt="screen shot 2018-12-06 at 11 40 14 am" src="https://user-images.githubusercontent.com/11523028/49605232-331aea00-f94d-11e8-9e47-c1bb23699166.png">

**Comment by ljarzynski** [comment]
just updated the screenshot on branches 2.0-master. Making it's way through the pipelines now. Closing this out. 

Thanks @mma-pivotal !
