### ISSUE TITLE
Small Footprint PAS docs omit Runtime CredHub

### ISSUE THREAD

**Issue by aclevername** [pivotal-cf/docs-pcf-install#543]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-3/customizing/small-footprint.html
We think this is inaccurate for small footprint PAS 2.0+

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Runtime CredHub is not mentioned. It is an optional component of PAS, and a default component on the Control VM of small footprint PAS.

**Describe the solution you'd like**
Update diagrams and docs to include Runtime CredHub.

**Describe alternatives you've considered**
none

**Additional context**
none

Best wishes
Jake and @jamesjoshuahill

**Comment by ljarzynski** [comment]
Hey @aclevername, thanks for bringing this up. 
I actually have a story in flight to address this very thing! 
I'll leave this issue open until I deliver the story

**Comment by ljarzynski** [comment]
Closing out this issue now. 
If you navigate to https://docs.pivotal.io/pivotalcf/2-3/customizing/small-footprint.html, you will now see the credhub vm is there.
