### ISSUE TITLE
Page not found when creating a pull request for documentation update

### ISSUE THREAD

**Issue by jgallucci32** [pivotal-cf/docs-pcf-install#551]
**Describe the bug**
When attempting to create a pull request to update documentation a "404" error is returned.

**To Reproduce**
1. Go to https://docs.pivotal.io/pivotalcf/2-3/customizing/azure-om-deploy.html
2. Scroll down to bottom of page
3. Click on 'Create a pull request or raise an issue on the source for this page in GitHub'
4. See Page not found (404) error

**Expected behavior**
Should take you to the Github page for the documentation and allow you to create an issue against that page.

**Screenshots**
![image](https://user-images.githubusercontent.com/9018897/47618654-c3365b80-da92-11e8-85b9-4bf9b929b6d6.png)

**OS, Browser, and Version:**
 - OS: Windows 10
 - Browser Chrome
 - Version 69.0.3497.100

**Comment by pspinrad** [comment]
Hi again @jgallucci32 -- sorry about that-- source location moved.  Try again, or else go to https://github.com/pivotal-cf/docs-ops-manager/blob/2.3/azure/config-manual.html.md.erb -- and thank you for trying to contribute, sorry you were thwarted...
