### ISSUE TITLE
Documentation for Azure deployment suggests deploying PAS (bosh VMs) to the Management network, not the deployment network

### ISSUE THREAD

**Issue by jgallucci32** [pivotal-cf/docs-pcf-install#552]
**URL or GitHub link to the page where you're having the issue**
https://github.com/pivotal-cf/docs-pcf-install/blob/2.3/azure-er-config.html.md.erb

**Describe the solution you'd like**
PAS tile should be deployed to "Deployment" network, not the Management one. This is best practice and consistent with documentation for deployment to other environments.

**Describe alternatives you've considered**
Alternative is to simply ignore the documentation which says to deploy to Management network and to deploy to the "Deployment" network.

**Additional context**
Here is the *incorrect* screenshot
![image](https://user-images.githubusercontent.com/9018897/48093189-8c172700-e1c3-11e8-8013-e9884efd6020.png)

**Comment by pspinrad** [comment]
Thank you @jgallucci32 -- could you screencap that dropdown with "PAS" or "deployment" network selected instead, post it here, and we'll swap it in? That would be super helpful-- thanks again.

**Comment by jgallucci32** [comment]
Here are two screenshots for you.
![image](https://user-images.githubusercontent.com/9018897/49255456-e8dfb900-f3e0-11e8-8581-2272a878ef2a.png)
![image](https://user-images.githubusercontent.com/9018897/49255490-04e35a80-f3e1-11e8-93c2-cccad4f4ad42.png)

**Comment by pspinrad** [comment]
Thanks again @jgallucci32 -- just swapped in the corrected screenshot (top one), all docs versions since v2.1-- will publish live soon.
