### ISSUE TITLE
In "Deploying PAS on GCP", add steps for generating CredHub encryption key

### ISSUE THREAD

**Issue by jakerg23** [pivotal-cf/docs-pcf-install#556]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-3/customizing/gcp-er-config.html

**Is your request for a change or addition to content related to a problem? If so, please describe.**
The user is directed to add an encryption key for CredHub, but no requirements or descriptions of what is required from a key name or value, or how to generate they key.

**Describe the solution you'd like**
Steps or requirements about the encryption key.

**Comment by animatedmax** [comment]
Hi @jakerg23 We've added a description and explanation. Thanks!
