### ISSUE TITLE
[Step 2 -> item 9] More instruction is required to configure director on Azure Stack

### ISSUE THREAD

**Issue by chenweienn** [pivotal-cf/docs-pcf-install#557]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-1/om/azure/config-manual.html#director-config
https://docs.pivotal.io/pivotalcf/2-1/om/azure/config-manual.html#azure-config

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Customer gets confused when following the procedure to install PCF on Azure Stack. The field "Tenant Management Resource Endpoint" is not clearly explained. 

**Describe the solution you'd like**
Give more explanation to help customer identify the correct value. It would be helpful if we can provide screenshot with example values presented for each field.
In practice, we referred the following guide:
https://community.emc.com/blogs/azurestack_guy/2018/08/01/getting-started-with-pcf-on-azurestack-asdk-part-2-configure-opsmanager,
and accordingly suggested that the value is indeed **(get-azurermcontext).Environment.ActiveDirectoryServiceEndpointResourceId**.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by pspinrad** [comment]
Thanks @chenweienn -- docs currently say:

> Enter the URL for your **Tenant Management Resource Endpoint**.

Following your pointer, what if it said:

> Enter the **Tenant Management Resource Endpoint** from your AzureRM Environment Context. This URL changes with every ASDK installation.

Would that help, or something else?  And what would a good example be?  Thanks again.

**Comment by pspinrad** [comment]
Made change I suggested above.
