### ISSUE TITLE
Uploading stemcell failed during Bosh Director install on vSphere

### ISSUE THREAD

**Issue by sarojraju** [pivotal-cf/docs-pcf-install#558]
**Describe the bug**
I am using PCF Ops Manager 2.3.3 - Build Number 194 to Deploy PCF Foundation on vSphere with administrator access. Bosh Director installation is keep on failing while uploading the stemcells.  All of my vSphere clusters are having DRS enabled, HA Admission control is 50%, Administrative previliages on vSphere But still its failing to upload the stemcells :

Below error details : 
Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/97.28'... Failed (00:01:17)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)
creating stemcell (bosh-vsphere-esxi-ubuntu-xenial-go_agent 97.28):
 CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"execution expired","ok_to_retry":false}
Exit code 1
===== 2018-11-18 15:24:30 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"; Duration: 96s; Exit Status: 1 

**To Reproduce**
1. Go to 'Ops Manager 2.3.3 Build :194 '
2. Click on 'Cofigure Bosh Director and Apply Changes'
3. Scroll down to 'End'

**Expected behavior**

**Screenshots**

**OS, Browser, and Version:**

**Additional context**
Add any other context about the problem.

**Comment by sarojraju** [comment]
Found the root cause as Ops Manager was not able to connect to the underlying ESX's and could not make API calls to upload stemcell.

**Comment by pspinrad** [comment]
Thanks @sarojraju -- I'm glad you found the cause.  Is there something we could add to the documentation to help others avoid the error?  Why couldn't your Ops Man connect?
