### ISSUE TITLE
Missing info for "Default stack (rootfs) for newly created apps" in 2.3.3+ 

### ISSUE THREAD

**Issue by lsilvapvt** [pivotal-cf/docs-pcf-install#559]
**Describe the bug**
Default stack config control was added to PAS tile (Cloud Controller panel) on 2.3.3 and documentation does not yet contain a reference to or explanation of the new feature.
```
   Default stack (rootfs) for newly created apps 
      o Platform default (currently 'cflinuxfs2')
      o cflinuxfs3
      o cflinuxfs2
```

**To Reproduce**
1. Go to 'https://docs.pivotal.io/pivotalcf/2-3/customizing/config-er-vmware.html#config-cc'
2. See that there is no reference of the new configuration option on that section.

**Expected behavior**
Configuration option for "Default stack (rootfs) for newly created apps" present on the docs page along with information on how platform operators should use it to implement/promote the migration from `cflinuxfs2` to `cflinuxfs3`.
This information should also be added to the PAS 2.4.0+ docs.

**Comment by pspinrad** [comment]
Thanks @lsilvapvt -- prioritized, and we'll be in touch.  Do you have an env that shows this, for us to screenshot?  Daily cheese doesn't include PAS tile.
