### ISSUE TITLE
vSphere Service Account Requirements for 6.7 - Unlock virtual machine

### ISSUE THREAD

**Issue by bgregor77** [pivotal-cf/docs-pcf-install#568]
**Describe the bug**

Some of the privileges have been changed for vCenter 6.7 and need to be updated. Specifically, "Unlock virtual machine" no longer exists. According to the documentation linked below you now need:
Cryptographic operations -> Register VM/Register host in order to perform the unlock operation.

Reference: https://docs.vmware.com/en/VMware-vSphere/6.7/vsphere-esxi-vcenter-server-67-security-guide.pdf

**Comment by cshollingsworth** [comment]
Hi, @bgregor77 ! Where in the docs do you see that this needs to be changed?

**Comment by mlimonczenko** [comment]
Hello @bgregor77,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
