### ISSUE TITLE
Ops Manager VM should be added to AWS requirements tables for PAS & Small Footprint PAS

### ISSUE THREAD

**Issue by hiremaga** [pivotal-cf/docs-pcf-install#575]
**URL or GitHub link to the page where you're having the issue**

https://github.com/pivotal-cf/docs-pcf-install/blob/2.4/aws.html.md.erb

**Is your request for a change or addition to content related to a problem? If so, please describe.**

The Ops Manager category for PAS and Small Footprint PAS mentions the BOSH Director VM but omits the Ops Manager VM.

**Describe the solution you'd like**

Add another row for the Ops Manager VM in both the PAS and Small Footprint PAS tables.

**Comment by mlimonczenko** [comment]
Hello @hiremaga,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
