### ISSUE TITLE
Cert chain example for director trusted certs

### ISSUE THREAD

**Issue by deadlysyn** [pivotal-cf/docs-pcf-install#577]
**URL or GitHub link to the page where you're having the issue**

https://docs.pivotal.io/pivotalcf/2-4/customizing/trusted-certificates.html

**Is your request for a change or addition to content related to a problem? If so, please describe.**

The current cert chain example doesn't make it clear what order intermediate/CA certs should be provided in.

**Describe the solution you'd like**

A simple note box or similar reference better showing the required order for pem encoded cert chains. 

e.g. director trusted certs needs Intermediate + CA in following order:

Wildcard
Intermediate
CA

**Describe alternatives you've considered**

Whatever you see fit, just want to save future readers time figuring out proper cert chain order.

**Additional context**

Apologies, I wanted to submit a PR but when I clicked the "submit" link at the bottom of the page it went to a markdown document containing a partial.  The path in the partial doesn't seem contained in this repo, and searching this repo for text on the target page didn't yield any results.  :-(

Reference:

https://www.digicert.com/ssl-support/pem-ssl-creation.htm

PS: Please thank Arron Hocking, Rahul Jain and Shawn Neal for this suggestion.

**Comment by mlimonczenko** [comment]
Hello @deadlysyn,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
