### ISSUE TITLE
Wrong Format in the Networking section. 

### ISSUE THREAD

**Issue by smcdnnll1** [pivotal-cf/docs-pcf-install#580]
@kdolor-pivotal 

The problem is located in the Networking section under no **30. Click Save.** 
https://docs.pivotal.io/pivotalcf/2-1/customizing/installing-pcf-is.html#networking
https://docs.pivotal.io/pivotalcf/2-2/customizing/installing-pcf-is.html#networking

This request is related to a problem with the documentation. Under number **30. Click Save** the format is incorrect. It is showing a lot of hyperlinks and format used within Github. 

If the documentation format could be changed to match that of the 2.3 Docs so that it is clearer to read. https://docs.pivotal.io/pivotalcf/2-3/customizing/installing-pcf-is.html#networking

**Comment by mjgutermuth** [comment]
Closing -- we are no longer editing the 2.1 and 2.2 docs. Thanks!
