### ISSUE TITLE
NSX-V version

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pcf-install#586]
**URL or GitHub link to the page where you're having the issue**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

**Is your request for a change or addition to content related to a problem? If so, please describe.**
A clear and concise description of the problem. For example: "Whenever I upgrade my software I forget to first collect information about the things I've already installed"

**Describe the solution you'd like**
A clear and concise description of what NSX-V versions we've tested with.  The following statement in 2.3 docs is old:
Note: Ops Manager v1.11 supports NSX-V v6.2 and later.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or content you've considered.

**Additional context**
Add any other context or screenshots about the content request here.

**Comment by mlimonczenko** [comment]
Hello @agregory999,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
