### ISSUE TITLE
Old PAS docs refer to 2.5.1 feature - gorouter bypass

### ISSUE THREAD

**Issue by coro** [pivotal-cf/docs-pcf-install#591]
**Describe the bug**
The PAS documentation for v2.2-2.5 all contain references to the 'Bypass security checks for route service lookup' feature. This feature was only released in PAS v2.5.1, and so should not be present in docs for versions 2.2-2.4.

**To Reproduce**
Visit any of:
https://docs.pivotal.io/pivotalcf/2-2/customizing/route-service-lookup.html#enable
https://docs.pivotal.io/pivotalcf/2-3/customizing/route-service-lookup.html#enable
https://docs.pivotal.io/pivotalcf/2-4/customizing/route-service-lookup.html#enable
https://docs.pivotal.io/pivotalcf/2-5/customizing/route-service-lookup.html#enable

**Expected behavior**
Only the 2.5 docs should mention 'Bypass security checks for route service lookup'. I do not know whether the entire page should only appear in 2.5, in addition.

**Screenshots**
N/A

**OS, Browser, and Version:**
 - OS: Mac OS
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by mlimonczenko** [comment]
Hello @coro,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
