### ISSUE TITLE
Does it necessary for ops manager director to be on same network with vCenter?

### ISSUE THREAD

**Issue by datianshi** [pivotal-cf/docs-pcf-install#6]
in the file - network-segmentation.html.md.erb

It was saying ops manager director need to be at the same network as vCenter, same showed in the pictures. I think as long as the network is routable, it would be fine. Never saw enterprise customers put their director to be on the same network as vCenter and it worked fine.

This may unnecessarily restrict the network requirements for PCF deployment. Thoughts?

**Comment by animatedmax** [comment]
Hi datianshi,

The network-segmentation.html.md.erb topic lists three options:
Option 1: Installing Pivotal CF Products to a Common Network
Option 2: Installing All Pivotal CF Products to an Isolated Network
Option 3: Installing Pivotal CF Products to Multiple Isolated Networks

Option 1 shows Ops Manager Director on the same network as vCenter, but both Option 2 and Option 3 show Ops Manager Director on a different network as vCenter. Option 1 also states that Production environments typically require higher security than this option provides.

Am I missing something?

Thanks!

**Comment by datianshi** [comment]
The docs said all the options with ops manager director and vCenter on the
same network.

From the picture:

Option 1: vCenter : 172.16.64.3. director:172.16.64.4
Option 2: vCenter : 172.16.64.3. director:172.16.64.10
Option 3: vCenter : 172.16.64.3. director:172.16.64.10

The word from the doc:

*You must multihome Ops Manager Director to receive two IP addresses, one
on each network*

While I mean the ops manager director does not have to be on the network as
the vCenter

**Comment by animatedmax** [comment]
Hi datianshi,

Ah, I see what you mean.

I've changed the wording in the document to say "You must configure Ops Manager Director to communicate on two networks, either through routing or by multihoming". This is more accurate than saying you must multihome Ops Manager Director to two networks.

Thanks!
