### ISSUE TITLE
PAS 2.6 does have a new option for file storage

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-pcf-install#603]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-6/customizing/pas-file-storage.html

**Is your request for a change or addition to content related to a problem? If so, please describe.**
PAS 2.6 did introduce a new bucket `Backup Bucket` for the File Storage when using an external storage.

**Describe the solution you'd like**
Update documentation and screenshots to include documentation for `Backup Bucket`

**Comment by mlimonczenko** [comment]
Hello @vchrisb,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
