### ISSUE TITLE
Add "BOSH DNS Certificate Authority Upgrades" procedure to Breaking Changes/PCF Upgrade page

### ISSUE THREAD

**Issue by pivotal-wesley-robertson** [pivotal-cf/docs-pcf-install#605]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/pivotalcf/2-3/customizing/upgrading-pcf.html
https://docs.pivotal.io/pivotalcf/2-3/pcf-release-notes/opsmanager-rn.html#bosh-dns-certs

**Is your request for a change or addition to content related to a problem? If so, please describe.**
The documentation for upgrading to PCF v2.3 should clearly indicate there is an extra step in the procedure to rotate BOSH DNS certificates. If this procedure is not followed (two apply changes) customers can see unpredictable behavior in the environment. 

**Describe the solution you'd like**
Add the content/procedure to the "Breaking Changes" *or* the main "Upgrading Pivotal Cloud Foundry" documentation for PCF 2.3. 

**Describe alternatives you've considered**
Knowledge base article was considered but this content is a deviation in the typical upgrade behavior. As such, it should be clearly noted in the breaking change/PCF upgrade doc. 

**Additional context**
https://docs.pivotal.io/pivotalcf/2-3/customizing/upgrading-pcf.html
https://docs.pivotal.io/pivotalcf/2-3/pcf-release-notes/breaking-changes.html
https://docs.pivotal.io/pivotalcf/2-3/pcf-release-notes/opsmanager-rn.html#bosh-dns-certs

**Comment by mlimonczenko** [comment]
Hello @pivotal-wesley-robertson,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
