### ISSUE TITLE
Apache NIFI as a PCF service

### ISSUE THREAD

**Issue by MohanBunny** [pivotal-cf/docs-pcf-install#61]
Hi,
I am just curious to know that is there any way to use Apache NIFI as service in Pivotal Cloud Foundry.
If it is,then how can we achieve it.What are the steps that we should follow.
Please give your valuable suggestions for the above.
Thank you,
Mohan.V

**Comment by bentarnoff** [comment]
See https://github.com/pivotal-cf/docs-pivotalcf-console/issues/5. Thanks.
