### ISSUE TITLE
Credentials for bosh CLI are not in the given link.

### ISSUE THREAD

**Issue by claudex** [pivotal-cf/docs-pcf-install#611]
**URL or GitHub link to the page where you're having the issue**

https://github.com/pivotal-cf/docs-pcf-install/blob/5a6b930c5d6b5bc5c4d95f42a807f331074f74d3/trouble-advanced.html.md.erb#L29

**Is your request for a change or addition to content related to a problem? If so, please describe.**

The credentials needed for the operation is the "Bosh Commandline Credentials" not the "Director Credentials"

**Describe the solution you'd like**
The text and the image should be changed

**Comment by mlimonczenko** [comment]
Hello @claudex,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
