### ISSUE TITLE
Revert Opsman Backup instructions seem incomplete

### ISSUE THREAD

**Issue by ingernet** [pivotal-cf/docs-pcf-install#626]
**URL or GitHub link to the page where you're having the issue**
https://github.com/pivotal-cf/docs-pcf-install/blob/2.5/modify-ops-man.html.md.erb

**Is your request for a change or addition to content related to a problem? If so, please describe.**
This is an addition of content. In the "Revert to Your Backup" (#revert) section of this doc, the user is instructed to replace the installation.yml file but not the actual-installation.yml file, even though the reverse process instructs the user to edit both files. I don't know if this breaks anything, but thought I should bring it up just in case.

**Describe the solution you'd like**
If the user needs to revert that file from backup, please call that out; otherwise, mention something about how it doesn't matter because of that file will get autogenerated or whatever. Having to guess on a thing like ops manager running config is a little nerve-wracking.

**Comment by mlimonczenko** [comment]
Hello @ingernet,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
