### ISSUE TITLE
looks like the phrase "PKS" got deleted from at least one OpsMan docs page

### ISSUE THREAD

**Issue by beckettsean** [pivotal-cf/docs-pcf-install#639]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/platform/2-8/customizing/viewing-logs-and-metrics.html

**Is your request for a change or addition to content related to a problem? If so, please describe.**
When reading the content on the page, there are multiple places where there's obviously a word or phrase missing, and from context I believe that phrase is always the string, "PKS"

e.g.
"There are also different permissions required to access logs and metrics on PAS and . "
"Access VM Logs on "
"Enable system logging in ."

**Describe the solution you'd like**
Replace the missing words with what they should be.

![Screen Shot 2020-03-04 at 15 16 46](https://user-images.githubusercontent.com/6537329/75928316-60de2f80-5e2b-11ea-8f08-5c4055d491c4.png)

**Comment by seviet** [comment]
thanks @beckettsean! we had a bad variable (undefined) in that page. update and repushed the live docs. https://docs.pivotal.io/platform/2-8/customizing/viewing-logs-and-metrics.html
