### ISSUE TITLE
bosh service account needs an additional permission when configuring GCP

### ISSUE THREAD

**Issue by kbrill11** [pivotal-cf/docs-pcf-install#91]
On this page: http://docs.pivotal.io/pivotalcf/1-8/customizing/gcp-prepare-env.html

bosh needs an additional permission, namely:
- **Project** > **Service Account Actor**

Otherwise the "Installing BOSH" step of these docs fails when clicking Apply:
http://docs.pivotal.io/pivotalcf/1-8/customizing/gcp-om-config.html

**Comment by seviet** [comment]
Hi @kbrill11! Thank you for reporting this. I will validate this with the eng team and get back to you!!

**Comment by seviet** [comment]
@kbrill11 Finally validated with engineering-- the Service Account Actor role is only required if you are using the Ops Manager VM Service Account option (and not AuthJSON) for the deployment. I have updated docs accordingly: 
http://docs.pivotal.io/pivotalcf/1-8/customizing/gcp-prepare-env.html#iam_account
http://docs.pivotal.io/pivotalcf/1-8/customizing/gcp-om-config.html#gcp-config

Thanks for the feedback!
