### ISSUE TITLE
no mention about issues with buildpack not beeing --lock during upgrade

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/docs-pcf-install#97]
Our PCF doc do not describe that any customer-updated buildpack will be overriden by the buildpack version in an Elastic runtime upgrade

As cf-release contains buildpack and is somewhat frozen in minor Elastic runtime version (1.7.1 as same cf-release as 1.7.12 etc) - this introduces the risk of version rollback  of buildpack

In Java buildpack this could even mean downtime - please see details scenario at https://gopivotal-com.socialcast.com/messages/32460413?ref=stream

**Comment by jncd** [comment]
Hi @avasseur-pivotal Thanks for logging this issue and the parallel CF issue. We'll look into it and make fixes to the docs.
